### ISSUE TITLE
Bug: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by mctweb** [harlan-zw/nuxt-simple-sitemap#1]
### Describe the bug

Bug was introduced here: https://github.com/harlan-zw/nuxt-simple-sitemap/commit/659a0d8a578708622f7a1316e5423fb3dd6dd6da

Error:
```
 ERROR  EISDIR: illegal operation on a directory, open 'C:\Users\Fraser\Websites\2022\mctweb.co.uk\.output\public\sitemap.xml'
```

When `nitro.options.prerender.routes.push("/sitemap.xml")`  is removed, the module works as expected

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 18.43 GB / 31.92 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.18.0 - ~\AppData\Roaming\npm\npm.CMD
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey thanks! Good catch, have fixed that up in 0.5.5.
