### ISSUE TITLE
nuxt run dev takes too long after adding dynamic URLs with options: urls

### ISSUE THREAD

**Issue by rendaiokada** [harlan-zw/nuxt-simple-sitemap#10]
### Details

I made a function that creates dynamic routes with various number of URLs. And, after this npm run dev started taking too long to process since it's generating the sitemap preview for each build. Is it possible to only generate a sitemap on nuxt build command?

```typescript
['nuxt-simple-sitemap',
    {
        hostname: process.env.BASE_URL,
        urls: () => {
            return Promise.all([
                axios.get(URL),
            ]).then(([courses]) => {
                return [
                    convertObjToSitemapByCourse(courses, 'course', 'monthly'),
                ].reduce((accumulator, currentValue) => accumulator.concat(currentValue), []);
            }).catch((e) => {
                console.log(e);
            });
        }
    }
]
```

**Comment by VladStepanov** [comment]
You can check NODE_ENV.
```js
urls: () => {
  if (process.env.NODE_ENV === 'production') {
    return []
  }
}
```

**Comment by rendaiokada** [comment]
> Hi, you can check `NODE_ENV`
> 
> ```js
> {
>   enabled: process.env.NODE_ENV === 'production'
>   urls: () => {
>     ...
>   }
> }
> ```

why didn't I come up with that!? Thank you!
