### ISSUE TITLE
How we can access to raw file generated by simple-sitemap module

### ISSUE THREAD

**Issue by NtchPlayer** [harlan-zw/nuxt-simple-sitemap#100]
### Details

Hi !
New user here ! On Nuxt 2, I use this plugin https://sitemap.nuxtjs.org/ to generate my sitemap.xml. I know there a nuxt 3 version of this plugin, but I prefer to try this new one, because your also create other plugin (like simple-robots), so I suppose it's better if we use then together !

So I setup the plugin for my usecase (I use i18n, and I use multiples sitemaps options), I have correctly have the urls like this on /sitemaps.xml and sub urk like /versions-sitemap.xml.
<img width="1440" alt="Capture d’écran 2023-07-29 à 12 00 46" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/64465776/303f691a-9259-49b5-ab57-9bb3a5916b65">

With https://sitemap.nuxtjs.org/ module, the sitemap generate more looks like a raw  xml file with <url> and <xhtml:link> (somehting like that: https://royal-gang-tv.vercel.app/sitemap.xml) tags.

It is possible to have the same style with this plugin ? I may ask because, even if the module detect my i18n locales ('en' and 'fr') like you can see in the screen above, only /en link are display, and no Hreflangs is detected. And I don't know if, is not better for SEO to have just have the raw file with all like instand of have page with style like this...

What show me debug page on my link generation, like you can see, alternatives property is correctly set.
<img width="429" alt="Capture d’écran 2023-07-29 à 11 58 25" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/64465776/21d11272-a95a-40e4-a32f-7c75fc28709b">

If you have any question feel free to ask ! I see that you are on the official Discord Server of NuxtJS, if you prefer to speak over there my pseudo is: @iceplayer (but there a no channel for sitemap discussion so I suppose it's better to ask here, it can help other people too).

**Comment by harlan-zw** [comment]
Hi @NtchPlayer 

What you're looking at when you view the sitemap.xml is a XLS file, think of it just like you would a CSS file for HTML.

Search engines completely ignore these stylesheets when reading the file. I based the module on Yoast SEO, the biggest SEO plugin for WordPress, so you can rest assured it has no negative side effects.

If you want to replicate what the search engine sees, you can right-click and view the page source. Alternatively, you have the option to disable XLS using:

```ts
export default defineNuxtConfig(() => {
  sitemap: {
    xsl: false
  }
})
```

If you just want to see the i18n data, you can always [modify the columns of the stylesheet](https://nuxtseo.com/sitemap/guides/customising-ui#example-adding-hreflang).

**Comment by NtchPlayer** [comment]
Thanks for your response ! View the source code is exactly what I want to check ! And thx for you other advices !
