### ISSUE TITLE
Type issue with `sitemaps` options

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-simple-sitemap#101]
### Describe the bug

The manual chunking example raise a type issue, https://nuxtseo.com/sitemap/guides/multi-sitemaps#manual-chunking.

The issue is 
![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/45267552/61bc1129-4ef3-4eca-9552-dd22bede133c)

### System / Nuxt Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 4.60 GB / 9.72 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.1 - /usr/bin/npm
    pnpm: 8.6.10 - ~/.local/share/pnpm/pnpm
```

**Comment by harlan-zw** [comment]
Thanks! The fix will be available in 3.1.1.
