### ISSUE TITLE
Preview fails on 3.1.0

### ISSUE THREAD

**Issue by luigigorlero** [harlan-zw/nuxt-simple-sitemap#103]
### Describe the bug

After updating from 3.0.15 to 3.1.0, `nuxi build` does not generate `nitro.json` making local preview fail.
My vercel build also failed, stating `No Output Directory named "dist" found after the Build completed`. Reverting back to 3.0.15 fixed the issue

**Comment by florianthiel** [comment]
I'm having the same issue. After upgrading to 3.1.0 Nuxt stops in the middle of the build process with no error. Vercel and Netlify deploys fail. Downgrading to 3.0.15 fixes the issue

**Comment by harlan-zw** [comment]
Hi guys, can you try out [v3.1.2](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v3.1.2) and see if you have any luck?

I haven't been able to replicate it, it seems like a really weird bug. If this version doesn't fix it can you provide some reproduction details like your sitemap / nitro config.
