### ISSUE TITLE
Expected behavior with i18n and redirect on root only

### ISSUE THREAD

**Issue by learntheropes** [harlan-zw/nuxt-simple-sitemap#105]
### Details

For the static routes, I notice that the behavior is different for the home page and for the other routes.

I notice that for the index page all 3 languages are listed but with the alternatives only for the default language.

For the other static routes, only the default language is listed, with the alternatives.

My i18n Settings are:
- languages: en, es, pt
- default language: es
- redirect on root only

Is this the expected behavior?

```xml
<url>
<lastmod>2023-07-30T06:38:19+00:00</lastmod>
<loc>http://localhost:3000/en</loc>
</url>
<url>
<xhtml:link rel="alternate" hreflang="en" href="http://localhost:3000/en"/>
<xhtml:link rel="alternate" hreflang="pt" href="http://localhost:3000/pt"/>
<loc>http://localhost:3000/es</loc>
<lastmod>2023-07-30T06:38:19+00:00</lastmod>
</url>
<url>
<lastmod>2023-07-30T06:38:19+00:00</lastmod>
<loc>http://localhost:3000/pt</loc>
</url>
<url>
<xhtml:link rel="alternate" hreflang="en" href="http://localhost:3000/en/history"/>
<xhtml:link rel="alternate" hreflang="pt" href="http://localhost:3000/pt/history"/>
<loc>http://localhost:3000/es/history</loc>
</url>
<url>
<xhtml:link rel="alternate" hreflang="en" href="http://localhost:3000/en/legal"/>
<xhtml:link rel="alternate" hreflang="pt" href="http://localhost:3000/pt/legal"/>
<loc>http://localhost:3000/es/legal</loc>
</url>
```

**Comment by harlan-zw** [comment]
Can you try with [v3.1.3](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v3.1.3), if you still have issues can you please make a reproduction based off of: https://stackblitz.com/edit/nuxt-starter-jwuie4?file=app.vue

**Comment by learntheropes** [comment]
I confirm this is resolved.

Thank you for the quick fix!
