### ISSUE TITLE
Defaults options are not apply with multiples sitemaps

### ISSUE THREAD

**Issue by NtchPlayer** [harlan-zw/nuxt-simple-sitemap#107]
### Describe the bug

When you sets defaults options into sitemaps objects, the options are not apply to url objects.

You can check it directly into the reproduction stackblitz. But like you can see in the two screens, my options are not apply to route object.

And It's not just a display problem like [i18n issue](https://github.com/harlan-zw/nuxt-simple-sitemap/issues/102), the options are not set into the source code of the page.

<img width="728" alt="Capture d’écran 2023-07-30 à 13 52 39" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/64465776/218f0085-bfbb-4740-b162-178055db4ef0">
<img width="394" alt="Capture d’écran 2023-07-30 à 13 53 20" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/64465776/2a3c5004-156c-4994-9f6e-0830a7f66642">

### Reproduction

https://stackblitz.com/edit/nuxt-starter-96kypb?file=nuxt.config.ts

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.6.4`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.8.1`
- Builder:          `vite`
- User Config:      `imports`, `vite`, `alias`, `runtimeConfig`, `telemetry`, `nitro`, `app`, `css`, `modules`, `pinia`, `i18n`, `build`, `sitemap`, `robots`, `vWave`
- Runtime Modules:  `@nuxtjs/eslint-module@4.1.0`, `@nuxtjs/i18n@8.0.0-beta.13`, `@nuxt/content@2.7.1`, `nuxt-simple-sitemap@3.0.15`, `@pinia/nuxt@0.4.11`, `@nuxtjs/color-mode@3.3.0`
- Build Modules:    `-`
```

**Comment by harlan-zw** [comment]
Hey, thanks for the issue/reproduction.

This is fixed in 3.1.3
