### ISSUE TITLE
Is it normal not to have a lastmod value for prerendered pages?

### ISSUE THREAD

**Issue by Chippd** [harlan-zw/nuxt-simple-sitemap#111]
### Details

<img width="1132" alt="image" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/6480754/c2fba907-ffd2-46dd-9d63-8c591337082d">

As per screenshot, I've a sitemap at [aihairstyles.com/sitemap.xml](https://aihairstyles.com/sitemap.xml) where the dynamically generated pages do not have a lastmod value. Google for some reason is refusing to index these pages and so trying to work out why and this jumped out at me. I've followed the steps in [prerendering](https://nuxtseo.com/sitemap/guides/prerendering) by adding `crawlLinks: true` in nuxt config, but no joy. 

Is this normal/ok? As per the docs it says it should add a [lastmod value](https://nuxtseo.com/sitemap/guides/prerendering#:~:text=add%20lastmod%20date%20(when%20autoLastmod%20isn%27t%20disabled).)

**Comment by harlan-zw** [comment]
Hi @Chippd, thanks for the issue.

Can you confirm which version you're using? It looks like quire an early version

**Comment by anirudhmurali** [comment]
We are in 2.4.0 and have the same issue - https://www.economize.cloud/resources/sitemap.xml

**Comment by harlan-zw** [comment]
> We are in 2.4.0 and have the same issue - [economize.cloud/resources/sitemap.xml](https://www.economize.cloud/resources/sitemap.xml)

Please use the latest and I can investigate further if it's not working

**Comment by harlan-zw** [comment]
Btw @Chippd, if you get in contact on Discord I'm happy to try and help you get your pages indexed, not having a lastmod isn't going to do anything.
