### ISSUE TITLE
`sitemap:resolved` runs twice

### ISSUE THREAD

**Issue by olivervorasai** [harlan-zw/nuxt-simple-sitemap#119]
### Describe the bug

Using the example provided here https://nuxtseo.com/sitemap/api/nitro-hooks, `/my-secret-url` is added twice. This is probably because the hook itself runs two times.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-26xgy1?file=server%2Fplugins%2Fsitemaps.ts

**Comment by harlan-zw** [comment]
Good catch, thanks!

Should be fixed in v3.1.6
