### ISSUE TITLE
nuxt 3.6.5 return error

### ISSUE THREAD

**Issue by andysay** [harlan-zw/nuxt-simple-sitemap#120]
### Describe the bug

<img width="1279" alt="Снимок экрана 2023-08-17 в 10 28 13" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/5610952/a110c8ea-1d95-4434-b47c-55be2aea964a">

### Reproduction

nuxt 3.6.5

### System / Nuxt Info

```Shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 372.56 MB / 32.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    npm: 9.6.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 16.1
```

**Comment by harlan-zw** [comment]
Hi, can you try create a reproduction https://stackblitz.com/edit/nuxt-starter-dyraxc?file=server%2Fapi%2F_sitemap-urls.ts :pray:

**Comment by harlan-zw** [comment]
Closing this as stale, feel free to re-open with a reproduction on latest Nuxt.
