### ISSUE TITLE
Manual chunking for multi-sitemaps not working 

### ISSUE THREAD

**Issue by VasanthThoraliKumaran** [harlan-zw/nuxt-simple-sitemap#122]
### Describe the bug

I'm using v3.2.4 and followed the doc to chunk sitemaps manually but it's not working as expected.

I tried include & exclude options in sitemaps. but It simply includes all entries in both sitemaps regardless of the given filter conditions.

```
  sitemap: {
    siteUrl: process.env.NUXT_PUBLIC_SITE_URL || "https://www.mywebsite.com",
    sitemaps: {
     foo: {
       //should only include /foo urls
        include: ['/foo/**']
      },
     bar: {
      //should only include /bar urls
        include: ['/bar/**']
      }
    }
  },
```

**Comment by VasanthThoraliKumaran** [comment]
- An alternative approach to filter URLs with respect to pages [nuxt hook](https://nuxtseo.com/sitemap/api/nuxt-hooks). It works
```
  hooks: {
    'sitemap:resolved': async (ctx) => {
      if (ctx.sitemapName == 'foo') {
        ctx.urls = ctx.urls.filter((item) => item.loc.includes('/foo'))
      }
      if (ctx.sitemapName == 'bar') {
        ctx.urls = ctx.urls.filter((item) => item.loc.includes('/bar'))
      }
    }
  },

```
- Closing it since related [PR](https://github.com/harlan-zw/nuxt-simple-sitemap/issues/96) already in open.

**Comment by harlan-zw** [comment]
The other issue is specifically related to using route matching with partial paths.

I've attempted to replicate the issue and it seems fine? https://stackblitz.com/edit/nuxt-starter-umyso3?file=nuxt.config.ts

Can you provide some more details
