### ISSUE TITLE
I18n sitemap mix the differents routes 

### ISSUE THREAD

**Issue by yuzu-qroulland** [harlan-zw/nuxt-simple-sitemap#123]
### Describe the bug

In the screenshots below, you can see that the /about-us route is shown in the FR site map, whereas it is an EN route..

### Generated sitemaps:

![Capture d’écran 2023-08-23 à 12 14 27](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/121189752/954265a5-4285-4eb9-ab4d-c43d9fe0a642)
_The FR sitemap_

![Capture d’écran 2023-08-23 à 12 14 41](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/121189752/686cc955-1754-4687-9704-032e4f5cbfb6)
_The EN sitemap_

### Custom routes configuration
```vue
defineI18nRoute({
  paths: {
    fr: '/a-propos',
    en: '/about-us',
  }
})
``` 

### I18n config
```vue
i18n: {
    strategy: "prefix_except_default",
    vueI18n: './i18n.config.ts',
    skipSettingLocaleOnNavigate: true,
    locales: [
      {
        code: 'fr',
        name: 'Français',
        iso: 'fr-FR'
      },
      {
        code: 'en',
        name: 'English',
        iso: 'en-US'
      }
    ],
    defaultLocale: 'fr',
  },
``` 

I don't have a sitemap configuration, have I forgotten something?

### System / Nuxt Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 142.92 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Edge: 114.0.1823.67
    Safari: 16.2
```

**Comment by parnaudd** [comment]
Hey !

 I also got this issue with `strategy: 'prefix'` on my side (with v3.2.5)

**Comment by eliaSchenker** [comment]
I also got this issue with prefix_except_default and custom route names.

**Comment by harlan-zw** [comment]
I've pushed up a fix that should improve the sitemap filtering depending on the locale.

However, there's a bug in the i18n module in mixing a prefixing strategy with `defineI18nRoute` that don't use prefixes. Until that is solved the sitemap module can't fix it. (the i18n module is creating prefixed and custom routes currently).

Saying that, you probably should reconsider how you're setting up your URLs if you want a prefixing strategy only sometimes.

**Comment by eliaSchenker** [comment]
@harlan-zw Thanks for your quick reply! The fix you provided worked perfectly for me, all localized urls are only in their respective language sitemap now, thanks!
