### ISSUE TITLE
Dynamic URLs are losing their final trailingSlash

### ISSUE THREAD

**Issue by juankamilo** [harlan-zw/nuxt-simple-sitemap#124]
### Details

I am observing that my imported urls from an external service [acording to](https://nuxtseo.com/sitemap/guides/dynamic-urls) , arrive correctly with their "/" at the end, but the sitemap generator is removing it, regardless of the "trailingSlash: true" setting, which I see is deprecated, in the last version (2.*) was working fine, is there any other way to keep this trailingSlash?. I can create URLs with double trailingSlash and works but.... 

It's a great module, good job
Thanks and regards

**Comment by harlan-zw** [comment]
Hi @juankamilo, can you please use the v3 latest? Seems to be working correctly https://stackblitz.com/edit/nuxt-starter-pfnpeb?file=nuxt.config.ts

**Comment by harlan-zw** [comment]
Thanks for confirming, will close this off.

**Comment by juankamilo** [comment]
Hi @harlan-zw sorry was on vacations, just see you close this but I test with the version 3.2.6 and still happens, i make a fork of your example so you can see it, hope is not to late xD, let me know if I can help 
https://stackblitz.com/edit/nuxt-starter-5g3qku?file=server%2Fapi%2F_sitemap-urls.ts

**Comment by harlan-zw** [comment]
Hi @juankamilo.

The issue with your code is that the module won't normalize URLs that are absolute. I've pushed a fix where it can normalize URLs that start with the site URL though, which should solve your issue. Available in 3.2.7.
