### ISSUE TITLE
"Sitemap could not be read" in Google Search Console.

### ISSUE THREAD

**Issue by learntheropes** [harlan-zw/nuxt-simple-sitemap#125]
### Details

I just deployed my sitemap with v3.2.6 and added to Google Search Console.

The generated sitemap looks valid with all the validators, but on Google Search Console I get:
```
Sitemap: https://booking.learntheropes.xyz/sitemap.xml
Type: Unknown 
Status: Couldn't fetch
Discovered pages 0
Sitemap could not be read
```
Has anyone experienced the same issue?
By searching around, I found out that this might be a Google issue, but I just want to check this is not due to some error in the generated xml.

**Comment by learntheropes** [comment]
The same happens also in another project I have here https://anybtcpay.learntheropes.xyz/sitemap_index.xml
With a very simple and auto-generated sitemap, without dynamic routes, as follows:
```xml
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>https://anybtcpay.learntheropes.xyz/en-sitemap.xml</loc>
<lastmod>2023-08-31T23:43:41+00:00</lastmod>
</sitemap>
<sitemap>
<loc>https://anybtcpay.learntheropes.xyz/es-sitemap.xml</loc>
<lastmod>2023-08-31T23:43:41+00:00</lastmod>
</sitemap>
<sitemap>
<loc>https://anybtcpay.learntheropes.xyz/it-sitemap.xml</loc>
<lastmod>2023-08-31T23:43:41+00:00</lastmod>
</sitemap>
</sitemapindex>
```
What could be the issue?

**Comment by harlan-zw** [comment]
I wonder if this is related to disabling the XLS, I haven't seen this on any of my sites using it.

![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/5326365/dfc52638-d340-4eb5-98f8-9ea880ffae2f)

**Comment by learntheropes** [comment]
After 24 hours, without any new deployment or change, the website of my second message is showing `Success`.

The first one still `Couldn't fetch`.

I will wait a bit longer to check if that get resolved alone as well, otherwise I will try what you suggest.

But at this point I doubt this is due to the module. Much probably is a google issue.

**Comment by AleeeKoi** [comment]
Same issue here after updating to the `3.2.6` , the index is correctly indexed but the localized on ca not be fetched.
@learntheropes are your sitemaps all indexed now?

**Comment by learntheropes** [comment]
@AleeeKoi the first one, that has a `/sitemap.xml` with all the translations, is not indexed yet. The second one, that has a `sitemap_index.xml` that links to 3 sitemaps one for language, has only 2 of them indexed.
I think this is due to google, not to this module, because I followed their faq suggest:
> Copy the sitemap URL from the Sitemaps report details page.
> Paste the URL into the [URL Inspection tool](https://search.google.com/search-console?action=inspect) and press Enter.
> Click Live test in the URL Inspection tool.
> Expand the Page availability section to see why Google isn't able to fetch the sitemap. You can find information about all the fields [here](https://support.google.com/webmasters/answer/9012289#live_indexable), but basically you want to see [Crawl](https://support.google.com/webmasters/answer/7643418) allowed? = "Yes", Page fetch = "Successful," and [Indexing](https://support.google.com/webmasters/answer/7645831) allowed? = "Yes".  

And they fetch all of them correctly, so the issue is on their side for not indexing it.

**Comment by MrTob** [comment]
Having the same issue

**Comment by AleeeKoi** [comment]
Mine are all indexed (urls are not fetched yet but this depends by google bot).

What I did, from the Google webmaster console, was remove my previous sitemap and then (manually) resubmit just the main `sitemap.xml`. Google discovered subsitemaps by itself and after about 1 hour all sitemaps are parsed without error.

idk if this is the correct procedure.. but it worked for me.

**Comment by learntheropes** [comment]
To fix my issue with the first website, I had to rename from `sitemap.xml` to `sitemap_index.xml` so google was forced to fetch again. This time it was accepted immediately. I will close the issue since this definitely related to google, not the mofule.

**Comment by szadave** [comment]
+1 for this in 2024.

**Comment by ebanDev** [comment]
Hi ! I'm having the same issue with https://github.com/mnl-syndicat/website & https://github.com/ebanDev/research-build-resist/

**Comment by harrinson-gutierrez** [comment]
> To fix my issue with the first website, I had to rename from `sitemap.xml` to `sitemap_index.xml` so google was forced to fetch again. This time it was accepted immediately. I will close the issue since this definitely related to google, not the mofule.

I've been having this problem for over two weeks, with my sitemap.xml not being recognized, so I changed the name, and it worked right away. Thanks.
