### ISSUE TITLE
i18n ignores definePageMeta({  i18n: false });

### ISSUE THREAD

**Issue by learntheropes** [harlan-zw/nuxt-simple-sitemap#126]
### Describe the bug

I don't know how common this scenario could be and hard to implement, but Let's say we have a project where some pages are translated and others are not because they have
```vue
definePageMeta({
  i18n: false
});
```
so that the structure of the website is:
```
/monolang
/es/multilang
/en/multilang
```
The module ignores this and creates the sitemap like if all the pages are multilanguage.
I created a simple reproduction.

In my real case, all the pages in the  `/admin` folder are mono language without lang suffix, but to exclude them from the sitemap instead of just providing the pages that actually exist, like so
```js
  sitemap: {
    exclude: ['/admin/**'],
    autoI18n: true
  },
```
I had to provide also the pages that the module thinks exist, like so
```js
  sitemap: {
    exclude: ['/admin/**', '/en/admin/**', '/es/admin/**'],
    autoI18n: true
  },
```
Really not a big issue or a priority to be honest.

### Reproduction

https://stackblitz.com/edit/nuxt-sitemap-r3ek9x?file=pages%2Fmonolang.vue&initialpath=es-sitemap.xml

**Comment by harlan-zw** [comment]
Was not aware of this way of disabling i18n on specific pages. Will keep this open and may support it if others need.

**Comment by reslear** [comment]
https://i18n.nuxtjs.org/guide/ignoring-localized-routes

**Comment by reslear** [comment]
@learntheropes is there some kind of workaround now?

**Comment by harlan-zw** [comment]
I aim to have this solved in a v4 which I'm currently working on.

**Comment by harlan-zw** [comment]
This is now supported in the [v4](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v4.0.0) release.

Let me know if you have any issues.
