### ISSUE TITLE
Sitemap urls don't have a trailing slash

### ISSUE THREAD

**Issue by kushsolitary** [harlan-zw/nuxt-simple-sitemap#128]
### Describe the bug

Hello,

This is my config

```ts
export default defineNuxtConfig({
  modules: [
    'nuxt-route-meta',
    '@nuxtseo/module',
    'nuxt-simple-sitemap',
    '@nuxtjs/plausible',
    'nuxt-link-checker',
    'nuxt-simple-robots'
  ],
  runtimeConfig: {
    public: {
      trailingSlash: true,
    }
  },
  app: {
    pageTransition: { name: 'page', mode: 'out-in' }
  }
})
```

However, the generated sitemap doesn't have trailing slashes on the page urls.

**Comment by pascalwengerter** [comment]
@kushsolitary came here because I wanted to point out that this config option is missing on https://nuxtseo.com/sitemap/api/config :D spend the last 20min figuring this out

You can simply, in your nuxt.config.{js,ts} do 
```
  sitemap: {
    trailingSlash: true,
  },
```

**Comment by kushsolitary** [comment]
@pascalwengerter thanks a lot this works perfectly! you saved my day :)
