### ISSUE TITLE
Custom BASE_URL can't set

### ISSUE THREAD

**Issue by mustafadilmac** [harlan-zw/nuxt-simple-sitemap#129]
### Clear and concise description of the problem

hello all and harlan, ı just need to set base_url for all my routes. it's basically get my current base_url and set it directly in to it. I just set custom things to forwarding things. I check all docs but cant find the how to set custom base_url. 

ı need this feature because ı have ngnix forwarding like http://xxx.com => https://www.xxx.com but my base url set http://xxx.com. 

@harlan-zw Thank you for everything you bring to the Vue community. You are great man 

### Suggested solution

sitemap: {
       base_url: 'HERE IT IS XXX.com',
        urls: [
            'placeholder'
        ],
        exclude: ['cookies', 'demo', 'terms-of-use', 'privacy-policy'],
    },

**Comment by harlan-zw** [comment]
Hi @mustafadilmac. Thanks for the issue and your kind words.

I think you may just need to set a site URL. I've updated the documentation to make it easier: https://nuxtseo.com/sitemap/getting-started/setting-site-url

Let me know if you have any issues.

**Comment by mustafadilmac** [comment]
Thanks for reply. 

ı try to see dev mode but when ı build and preview my problem solved. Site url set only on **production mode**

in NUXT 3

`npm run build`
`npm run preview`

**Comment by mustafadilmac** [comment]
Thanks for reply. 

ı try to see dev mode but when ı build and preview my problem solved. Site url set only on **production mode**

`site: {
url: 'https://www.example.com' 
}`

in NUXT 3

`npm run build`
`npm run preview`

**Comment by harlan-zw** [comment]
Hey, in development you can click the link 

> You can preview your canonical sitemap by visiting /sitemap_index.xml?canonical

 and it will show you the URL for production.

![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/5326365/3afabb76-088e-44d0-99a4-10ef7592e94b)
