### ISSUE TITLE
`inferStaticPagesAsRoutes` lose efficacy

### ISSUE THREAD

**Issue by lxccc812** [harlan-zw/nuxt-simple-sitemap#132]
### Describe the bug

I use dynamic urls to configure sitemap information,I set `inferStaticPagesAsRoutes` to false, but it doesn't seem to work. Is there something wrong with my configuration? Maybe I should use exclude.

My configuration information
```ts
export default defineNuxtConfig({
    modules: ['nuxt-simple-sitemap'],
    site: {
        // url: process.env.NUXT_PUBLIC_SITE_URL,
        url: 'http://localhost:3000/',
        inferStaticPagesAsRoutes: false,
    },
    sitemap: {
        // xsl: false,
        // cacheTtl: 1000 * 60 * 60 * 24, // 1 day
        cacheTtl: 1000 * 10, // 10 s
        inferStaticPagesAsRoutes: false,
        // runtimeCacheStorage: {
        //     driver: 'redis',
        //     host: 'localhost',
        //     port: 6379,
        //     db: 0,
        // },
    },
})
```

result
![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/110974969/f24fd23a-ebf6-4703-a6a8-042f32ba39f2)

My pages directory structure
/pages
 --c
 ----[cateogryName]

I want to ignore all routes under pages

### Reproduction

none

### System / Nuxt Info

```Shell
nuxt:  3.7.1
nuxt-simple-sitemap: 3.2.7
```

**Comment by harlan-zw** [comment]
Are you able to provide a reproduction? You can use https://stackblitz.com/edit/nuxt-starter-dyraxc?file=server%2Fapi%2F_sitemap-urls.ts as a starter 

The page inferring should never add dynamic routes even if it's on so something is quite wrong.

**Comment by lxccc812** [comment]
[reproduction](https://stackblitz.com/edit/nuxt-starter-iixmyn?file=nuxt.config.ts)    

routeRules when used with sitemap, `inferStaticPagesAsRoutes` not working

**Comment by harlan-zw** [comment]
So this is a bug with how the route rules are used. It shouldn't add any URLs with params. I've pushed up a fix for it.
