### ISSUE TITLE
GoogleNewsEntry ETA?

### ISSUE THREAD

**Issue by Namstel** [harlan-zw/nuxt-simple-sitemap#133]
### Details

Hey,

I was looking to use this great module to also include Google News Entries, so in the docs I found the [schema](https://nuxtseo.com/sitemap/api/schema) including the `news` key. Great!

But after a lot of struggling and debugging to get it to work, I finally found this line in the source code with no case for `news` 😅
https://github.com/harlan-zw/nuxt-simple-sitemap/blob/188ec5cd452d7931935224bc3dd167a4373b9136/src/runtime/sitemap/builder/sitemap.ts#L21

Do you have an ETA for when that feature will be implemented? Or is there a way I can add it by hand somehow?

I'd be very happy to hear from you! Thanks for all your hard work.

**Comment by harlan-zw** [comment]
Hey, available in 3.3.0, let me know if you have any issues. It's worth noting that I updated the schema to match the spec closer.

```ts
{
  loc: 'https://nuxtseo.com/',
  news: {
    publication: {
      name: 'Nuxt SEO',
      language: 'en',
    },
    title: 'Nuxt SEO',
    publication_date: '2008-12-23',
  },
},
```
