### ISSUE TITLE
Sitemap generation for dynamic URLs limited to 1000 pages only

### ISSUE THREAD

**Issue by charbs-io** [harlan-zw/nuxt-simple-sitemap#137]
### Details

Hi there, 

I've been trialling this module (it's amazing, thank you!).

I am fetching dynamic URLs from a supabase table. I expect there to be around 6000 entries in the sitemap, but for some reason i end up with 1003 entries (1000 are dynamic, and then 3 static pages).

Here's my `server/api/_sitemap-urls.ts` endpoint.
```
import { serverSupabaseClient } from "#supabase/server";

export default defineEventHandler(async (event) => {
  const client = await serverSupabaseClient(event);

  const { data } = await client.from("posts").select("*");

  return data.map((p) => {
    return { loc: `/posts/${p.slug}`, lastmod: p.updated_at };
  });
});
```

I've also tried [multi sitemaps](https://nuxtseo.com/sitemap/guides/multi-sitemaps), but it's simply splitting my entries into 1000 and then 3 in the next sitemap.

Does anyone know if i am hitting some internal nuxt and/or nuxt-simple-sitemap limits?

Thanks

**Comment by harlan-zw** [comment]
> I'm really sorry, I've been looking at this issue for 4 hours... And 5 minutes after posting this, I realised this is actually a default setting from Supabase...
> 
> > By default, Supabase projects return a maximum of 1,000 rows. This setting can be changed in your project's [API settings](https://supabase.com/dashboard/project/_/settings/api). It's recommended that you keep it low to limit the payload size of accidental or malicious requests. You can use range() queries to paginate through your data.

Good catch, glad you could fix it 🙂
