### ISSUE TITLE
Is it possible to generate sitemap again

### ISSUE THREAD

**Issue by alimozdemir** [harlan-zw/nuxt-simple-sitemap#14]
### Details

Hello there, I have one question regarding dynamic sitemap generation.

I have been using the sitemap:urls function for applying dynamic content to sitemap.xml. It is working very well in the dev environment but whenever I send it to the production environment it generates a sitemap in the build pipeline and later it is not updating the sitemap by this method. 

So, what I expect from sitemap:urls method is actually it should be invoked and sitemap.xml should be updated after the app starts. Is it possible to do that?

Best regards,
Alim

**Comment by harlan-zw** [comment]
Hey @alimozdemir, thanks for the issue :)

With the v2 release, you are now able to have a dynamic SSR sitemap. You will need to switch to using either the API endpoint (see [Handling dynamic URLs](https://github.com/harlan-zw/nuxt-simple-sitemap#handling-dynamic-urls)) or if you prefer using hooks, you can use the [Nitro hook](https://github.com/harlan-zw/nuxt-simple-sitemap#nitro-hooks).

For a dynamic sitemap to work, you will also need to deploy your app with `nuxt build` and avoid prerendering it.
