### ISSUE TITLE
fix: `site.url` seems not to be used

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/nuxt-simple-sitemap#140]
### Describe the bug

Given then reproduction linked below, I'd expect the sitemap to be about "example.com" not "localhost" as set in the nuxt config. Am I doing something wrong? I'm pretty sure it worked as expected before.

### Reproduction

https://stackblitz.com/edit/github-3gjye4?file=pages%2Findex.vue

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, modules, site
- Runtime Modules:  nuxt-simple-sitemap@3.3.4
- Build Modules:    -
------------------------------
```

**Comment by dargmuesli** [comment]
I did some trial and error and found that this issue was introduced in `nuxt-site-config` v`1.2.3`

**Comment by harlan-zw** [comment]
Hey, thanks for the issue.

It seems like it's working correctly as far as I can tell. Keep in mind that it shows localhost when working in development, this allows you to click into the links for debugging purposes. You can click the `?canonical` link and it will switch to using the configured URL.

![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/5326365/65bb35ca-ee62-47cb-acb1-07d9052b6364)

Or have I missed something?

**Comment by dargmuesli** [comment]
Hmm, don't know why it works now. I opened the issue in https://github.com/harlan-zw/nuxt-seo-kit/issues/112 as a second try :thinking:
