### ISSUE TITLE
Automatically send/ping sitemap to search engines after site build

### ISSUE THREAD

**Issue by stefanobartoletti** [harlan-zw/nuxt-simple-sitemap#146]
### Clear and concise description of the problem

It would be great if the generated sitemap could be automatically sent to Google (and possibly other search engines) after a site build and deploy.

It is as easy as pinging an URL, like this:

```
https://www.google.com/ping?sitemap=FULL_URL_OF_SITEMAP
```

### Suggested solution

At the  moment I'm using a Netlify plugin to achieve this ([this one](https://www.netlify.com/integrations/community-built/submit-sitemap-build-plugin/)), but I would prefer to have all my configuration in one place, and since there is already Nuxt Seo for handling sitemaps, it would be great if it could also integrate this feature. Plus, the Netlify plugin is of course only available on Netlify and not on other platforms.

Reference:
https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap#addsitemap

Thanks 🙏🏻

**Comment by harlan-zw** [comment]
This is a great idea, thanks for the suggestion.

**Comment by stefanobartoletti** [comment]
Thanks to you, your set of SEO modules is awesome and really needed 👍🏻

**Comment by davidstackio** [comment]
Unfortunately, it looks like the ping endpoint is going away in December 2023: https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping

**Comment by stefanobartoletti** [comment]
@davidstackio thanks for sharing this.

I guess that this feature is no longer needed then.

According to that article, the most important thing now is the `lastmod` attribute and correctly setting its value.

**Comment by harlan-zw** [comment]
Good to know, thanks.

With this information, I'm going to close this issue off as well as:
- disable `autoLastmod` by default (in v4.1)
- add best practices page https://nuxtseo.com/sitemap/guides/best-practices
