### ISSUE TITLE
dynamic site url behind proxy

### ISSUE THREAD

**Issue by niddu85** [harlan-zw/nuxt-simple-sitemap#147]
### Details

Hello,
i have a nuxt 3 website that serves different domains, eg:
https://www.site1.com
https://www.site2.com
https://www.site3.com

the node instance it's behind a reverse proxy (IIS with urlrewrite module) with the follwing rules:
https://www.site1.com -> proxy to http://www.site1.local:3000
https://www.site2.com -> proxy to http://www.site2.local:3000
https://www.site3.com -> proxy to http://www.site3.local:3000

what happens is the sitemap module returns as the base address the "local" address eg:

http://www.site1.local:3000/Login

how and where can i set the site url at runtime in Nuxt 3? 
I am able to read the original url (www.site1.com) using headers in event.node.req.headers

PS: sitemap will be exactly the same for all websites,

thanks in advance

**Comment by harlan-zw** [comment]
Hey @niddu85

This module uses [nuxt-site-config](https://github.com/harlan-zw/nuxt-site-config) to handle the site URL. This module was built to support multi-tenancy like you have. 

You would do something like this, although I'd recommend opting for a switch statement.  The reason why it doesn't use the request host directly is that the URLs need to use the canonical site URLs.

```ts
import { defineNuxtPlugin, updateSiteConfig, useRequestURL } from '#imports'

export default defineNuxtPlugin({
  enforce: 'post',
  setup() {
    const url = useRequestURL()
    updateSiteConfig({
      url: url.origin,
    })
  },
})
```

There may be some issues around the caching with this though, I'll need to look into that further. For now, you can disable caching with `sitemap: { cacheTtl: false }`.

Let me know how you go! Keen to get this working in a multi-tenancy setup.

**Comment by niddu85** [comment]
Yes, in the end I was able to solve it exactly with the solution you explained.
What was preventing to work correctly was exactly the cache so I disabled it and started working.
What I suggest you is to clear the cache when updateSiteConfig

Thanks for your hint

**Comment by harlan-zw** [comment]
> Yes, in the end I was able to solve it exactly with the solution you explained. What was preventing to work correctly was exactly the cache so I disabled it and started working. What I suggest you is to clear the cache when updateSiteConfig
> 
> Thanks for your hint

Ideally, it would cache based on the site URL, but yes I agree :)

**Comment by harlan-zw** [comment]
The caching should now be fixed in [v4](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v4.0.0). It uses SWR cache and should cache based on the request origin headers.
