### ISSUE TITLE
Add entries to sitemap based on middleware

### ISSUE THREAD

**Issue by jf908** [harlan-zw/nuxt-simple-sitemap#148]
### Clear and concise description of the problem

In my Nuxt project, I have a middleware for only allowing logged in users on specific pages, specified in the definePageMeta. Right now, I have to remember each time and manually add pages to the sitemap if they are public. I think it would be a great feature to be able to optionally add things to the sitemap depending on what a page's meta is.

### Suggested solution

Provide a config value that is a function that takes as input the contents of definePageMeta and outputs a boolean that decides whether to include the page and all of its inner paths in the sitemap or not. I'm not technically familiar with the Nuxt API so perhaps there is a better alternative?

**Comment by harlan-zw** [comment]
Hi @jf908, sorry for the delay.

I'd recommend that you use the `index: false` route rule for any authenticated routes. I'd also recommend putting all of your authenticated routes under some sort of URL pattern then you can match them using wild cards.

For example:

```ts
export default defineNuxtConfig({
  routeRules: {
    '/my-account/**': { index: false }
  }
})
```

You can also provide these at a page level.

```ts
defineRouteRules({
   index: false
})
```

If you're using [Nuxt Simple Robots](https://github.com/harlan-zw/nuxt-simple-robots) this will also make sure these URLs aren't indexed by search engines.

Will close for now as I think these work arounds are good enough.

**Comment by jf908** [comment]
Thank you for your response. The problem I am trying to solve is that I would prefer to be able to use 1 line of code to set both the middleware and the routeRules because its possible that a developer will forget to set one or the other so I want someway of implying both.

Since definePageMeta is a macro, you can't add setup a way to do this automatically. After thinking about it though, this is a more an issue with Nuxt's architecture so I don't think this plugin is responsible for addressing this, thanks.
