### ISSUE TITLE
Sitemap not indexing properly on Vercel

### ISSUE THREAD

**Issue by stephanepericat** [harlan-zw/nuxt-simple-sitemap#152]
### Describe the bug

I have installed version 3.4.0 in my Nuxt .3.7 project. The sitemap works find on local, but when I deploy it to vercel, I just see some empty lines (see link in "reproduction field"). I did add ` NUXT_PUBLIC_SITE_URL` as an environment variable.

### Reproduction

https://covid-conscious-preview.vercel.app/sitemap_index.xml

### System / Nuxt Info

```Shell
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      app, modules, runtimeConfig, cloudflareAnalytics, inkline, i18n, sanity, supabase, turnstile
- Runtime Modules:  @inkline/plugin/nuxt@1.5.2, @nuxtjs/i18n@8.0.0-rc.4, @nuxtjs/sanity@1.8.1, @nuxtjs/turnstile@0.6.3, nuxt-cloudflare-analytics@1.0.8, nuxt-icon@0.5.0, @nuxtjs/supabase@1.1.2, @nuxtjs/robots@3.0.0, nuxt-simple-sitemap@3.4.0
- Build Modules:    -
```

**Comment by harlan-zw** [comment]
Hi @stephanepericat 

Can you provide your sitemap config? Ideally a reproduction using one of the StackBlitz starters would help me provide support quicker.

**Comment by stephanepericat** [comment]
code can be found here: https://github.com/stephanepericat/covid-conscious/blob/main/nuxt.config.ts#L26 i basically did not setup any explicit config for the module. But it does work locally:
<img width="1792" alt="Screen Shot 2023-10-21 at 9 05 44 PM" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/161823/17ae07f1-2475-4778-a4c7-2354fa649a5f">
<img width="1792" alt="Screen Shot 2023-10-21 at 9 05 48 PM" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/161823/a3f1438f-bbae-4f8c-adcb-9f54fd2fd5a6">

**Comment by stephanepericat** [comment]
I think my issue might be similar to this one: https://github.com/harlan-zw/nuxt-simple-sitemap/issues/151

**Comment by harlan-zw** [comment]
Check your i18n baseUrl, that needs to be absolute.

**Comment by stephanepericat** [comment]
hi @harlan-zw ;

you were right :)

I updated my i18n config as such:

```
baseUrl: `${process.env.NUXT_PUBLIC_SITE_URL}/`,
```

And now it works :) https://covid-conscious-preview.vercel.app/sitemap_index.xml

Thanks a lot!!
