### ISSUE TITLE
Support locales `domain` property (i18n)

### ISSUE THREAD

**Issue by lujiankang0602** [harlan-zw/nuxt-simple-sitemap#155]
### Details

在生成站点地图时，配置的i18n是在链接前面加前缀，我想要的是不加前缀，而是直接更换域名
When I use his i18n, it adds prefixes to the paths of each language. I want to use the domain names of each language instead of adding prefixes when generating the site map.

**Comment by harlan-zw** [comment]
This is now supported in the [v4](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v4.0.0) release. Let me know if you have any issues.

**Comment by lujiankang0602** [comment]
I did not see any support for the language environment domain attribute (i18n) of sitemap in the document

@harlan-zw

**Comment by lujiankang0602** [comment]
I did not see any information in the document regarding the language environment domain attribute (i18n) of sitemap

@harlan-zw

**Comment by harlan-zw** [comment]
Well it's not documented fully because it's a I18n feature, I mention it on this page: https://nuxtseo.com/sitemap/integrations/i18n#automatic-i18n-multi-sitemap

Just provide the domain on the locale and make sure you set `differentDomains: true`

**Comment by gaoxu529** [comment]
@harlan-zw 
这是当i18n DifferentDomains 为True时生成的站点地图，如下图所示：
![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/5687897/fa79c088-56ab-4ad6-bd44-65ed554ce36d)
然而，正确的格式应该是这样的：
```
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/__sitemap__/style.xsl"?>
  <urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
  <changefreq>hourly</changefreq>
  <lastmod>2023-11-20T09:42:24+00:00</lastmod>
  <loc>https://www.footballant.com/</loc>
 <xhtml:link rel="alternate" hreflang="en" href="https://www.footballant.com/" />
  <xhtml:link rel="alternate" hreflang="fr" href="https://fr.footballant.com/" />
   <xhtml:link rel="alternate" hreflang="x-default" href="https://www.footballant.com/" />
   </url>
   <url>
   <changefreq>hourly</changefreq>
   <lastmod>2023-11-20T09:42:24+00:00</lastmod>
   <loc>https://www.footballant.com/about</loc>
   <xhtml:link rel="alternate" hreflang="en" href="https://www.footballant.com/about" />
   <xhtml:link rel="alternate" hreflang="fr" href="https://fr.footballant.com/about" />
   <xhtml:link rel="alternate" hreflang="x-default" href="https://www.footballant.com/about" />
   </url>
</urlset>
```
