### ISSUE TITLE
`Exclude`d routes still appear in sitemap for prerendered pages

### ISSUE THREAD

**Issue by pascalwengerter** [harlan-zw/nuxt-simple-sitemap#156]
### Describe the bug

Similar to https://github.com/harlan-zw/nuxt-simple-sitemap/issues/71 - we're using Nuxt to generate a large-ish website including blog posts and, in general, a lot of prerendered pages to serve statically, some of which should be excluded from the final sitemap. 
We originally tried generating the sitemap by fetching our pages from the headless CMS, but that wouldn't work because we don't run a Node server but simply serve the SSG assets. The result was that all routes for all pregenerated/prerendered pages would end up in the sitemap.
Now, we switched to a `exclude` string array for routes that we don't want in the sitemap as a quick workaround, but unintuively all all routes for all pregenerated/prerendered pages end up in the sitemap. Disabling `inferStaticPagesAsRoutes` wouldn't help either, because then we'd have to partition (and hardcode) all our ~800 pages in `include` and `exclude`?

This issue is basically three things:
1. A question on "how does this plugin work", and/or "in which order do the sitemap generation steps happen". I guess the documentation could be improved in that point
2. A  potential bug since "it does not work as expected" - `exclude` doesn't work for pregenerated pages?
3. A clarification question on "how can I achieve what I want" 😉 how can I, for a setup with headless CMS and static site generation, sort my pages' routes to appear (or be hidden) in the sitemap, using this library 🙂 

Thank you in advance!

### System / Nuxt Info

```Shell
- Node Version:     v18.13.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
```

**Comment by harlan-zw** [comment]
Hi please try the [v4](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v4.0.0), I believe the logic is more sound for what you're trying to accomplish. Also, the docs have been updated so they should hopefully answer your questions.

Let me know if you still have issues.
