### ISSUE TITLE
feature request: add filtering in sitemaps by `key` and `callback`

### ISSUE THREAD

**Issue by reslear** [harlan-zw/nuxt-simple-sitemap#157]
### Clear and concise description of the problem

There is one suggestion, of course it can be realized a level higher, but I would like a built-in solution in the already existing functionality sitemaps:
if I have for example a root `pages/[slug].vue` with slags:

```ts
// server/api/_sitemap-urls.ts
const sitemap: SitemapEntry[] = landings.map((page) => {
  return {
    loc: '/' + page.slug,
    changefreq: 'weekly',
    priority: 0.9,
    lastmod: page.updatedAt,
  }
})
```

```ts
// nuxt.config.ts
sitemaps: {
  landings: {
    include: ['/**'],
    defaults: { priority: 0.7 },
  },
  pages: {
    exclude: [
      '/**',
    ],
  },
},
```

### Suggested solution

maybe in the future need to add a `key` like unhead meta key: 

```ts
// server/api/_sitemap-urls.ts
const sitemap: SitemapEntry[] = landings.map((page) => {
  return {
    loc: '/' + page.slug,
    changefreq: 'weekly',
    priority: 0.9,
    lastmod: page.updatedAt,
    key: "landing"
  }
})
```

```ts
// nuxt.config.ts
sitemaps: {
  landings: {
    include: [
      ({ key }) => key === 'landing'
    ],
    defaults: { priority: 0.7 },
  },
  pages: {
    exclude: [
      ({ key }) => key === 'landing'
    ],
  },
},
```

in the output key is simply not used in sitemap or only for debugging 

Sitemap | Last Modified
-- | --
http://localhost:3010/landings-sitemap.xml | 2023-10-19 15:09 +00:00
http://localhost:3010/pages-sitemap.xml | 2023-10-30 16:39 +00:00

### Also maybe need add auto-exclude key like `omitFromRest`: 

 ```ts
// nuxt.config.ts
sitemaps: {
  landings: {
    include: [
      ({ key }) => key === 'landing'
    ],
    defaults: { priority: 0.7 },
    omitFromRest: true
  },
  pages: {
    // no need write exclude
  },
},
```

it all seems like syntactic sugar but you can vote :) 

thx @harlan-zw for good lib :)

**Comment by harlan-zw** [comment]
In the new [v4] release you can provide a `_sitemap` key which will put it in that sitemap.

You can read more about it [here](https://nuxtseo.com/sitemap/guides/multi-sitemaps#extending-app-sources).

Let me know if you have any issues.

**Comment by reslear** [comment]
awesome 🔥🔥🔥
