### ISSUE TITLE
Incompatibility when using nuxt 3.6.5

### ISSUE THREAD

**Issue by MuhamadAdrian** [harlan-zw/nuxt-simple-sitemap#158]
### Describe the bug

I have a project that uses nuxt 3.6.5. And I can't upgrade it because there are other dependencies that don't support nuxt version 3.7.0 or 3.8.0. But I need the sitemap plugin to use on nuxt 3. For now this is all I found. Can you make this work on nuxt 3.6.0 ? Because basically nuxt 3.6 is nuxt 3 too

**Comment by harlan-zw** [comment]
You can use earlier versions of Nuxt Simple Sitemap, such as ones in the 2.x range if you need to support earlier versions of Nuxt.

Otherwise I can't do anything about this sorry. There shouldn't be any breaking changes between 3.7 or 3.8 so not sure what the problem is.

**Comment by MuhamadAdrian** [comment]
Okay. Thanks for the reply
