### ISSUE TITLE
Video Schema does not allow for multiple `<video:tag>`?

### ISSUE THREAD

**Issue by chrisspiegl** [harlan-zw/nuxt-simple-sitemap#159]
### Describe the bug

The Schema for video by Google (https://developers.google.com/search/docs/crawling-indexing/sitemaps/video-sitemaps look at: `<video:tag>`)  allows for multiple tag elements.

Though when adding an array of strings to the video.tag element, it will not work.

```js
videos: [{
        title: data.title,
        thumbnailLoc: data.thumbnail.url,
        description: data.excerpt,
        live: false,
        tag: data.tags,
      }],
```

Expected behavior would be to add multiple `<video:tag>` so that multiple tags can be set on a video file.

Warm regards,
Chris

**Comment by harlan-zw** [comment]
This is now supported in the [v4](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v4.0.0) release.

Let me know if you have any issues.

**Comment by chrisspiegl** [comment]
Sorry for the insane delay. But I wanted to confirm that this is indeed fixed as I finally was able to update our code base to have this feature.

Thank you.
