### ISSUE TITLE
[2.x] Error while building the app

### ISSUE THREAD

**Issue by rcerljenko** [harlan-zw/nuxt-simple-sitemap#16]
### Describe the bug

After updating to v2.0.2 and running `nuxt build` this happens (while building Nitro server):
```
RollupError: Could not resolve "../../page-utils" from "node_modules/nuxt-simple-sitemap/dist/runtime/util/entries.mjs"  
```

### System / Nuxt Info

```Shell
Nuxt: v3.1.3
Nitro: v2.3.1
Sitemap: v2.0.2
```

**Comment by Barbapapazes** [comment]
Yes, same error here 
![image](https://user-images.githubusercontent.com/45267552/225743880-ce5b36b0-f423-4a10-baed-5554dd6f4f8e.png)

**Comment by Barbapapazes** [comment]
Here a reproduction to view the error, juste start the project with npm run dev and the error appear

https://stackblitz.com/edit/github-rp5jz9?file=package-lock.json

**Comment by kkan0615** [comment]
I have a same issue.
```
 ERROR  RollupError: Could not resolve "../../page-utils" from "node_modules/nuxt-simple-sitemap/dist/runtime/util/entries.mjs" 
```

Nuxt 3.3.1 version

**Comment by harlan-zw** [comment]
Thank you for the issue. I should probably avoid releasing things at 3am in the morning :facepalm: 

Please use the latest version and it should be fixed
