### ISSUE TITLE
nuxt.config.ts type error in routeRules

### ISSUE THREAD

**Issue by jf908** [harlan-zw/nuxt-simple-sitemap#160]
### Describe the bug

I get this type error when I use `index: false` in my nuxt.config.ts's routeRules:

```
Type '{ index: false; }' is not assignable to type '{ cache?: false | { swr?: boolean | undefined; name?: string | undefined; group?: string | undefined; integrity?: any; maxAge?: number | undefined; staleMaxAge?: number | undefined; base?: string | undefined; headersOnly?: boolean | undefined; varies?: (string | undefined)[] | undefined; } | undefined; ... 9 more .....'.
  Object literal may only specify known properties, and 'index' does not exist in type '{ cache?: false | { swr?: boolean | undefined; name?: string | undefined; group?: string | undefined; integrity?: any; maxAge?: number | undefined; staleMaxAge?: number | undefined; base?: string | undefined; headersOnly?: boolean | undefined; varies?: (string | undefined)[] | undefined; } | undefined; ... 9 more .....'.(2322)
```
~~Can the routeRules interface be extended to support the index and sitemap keys?~~

I see that the package extends NitroRouteRules so perhaps this is a nuxt error or it has broken in 3.8.

### Reproduction

https://stackblitz.com/edit/github-vbgetm?file=nuxt.config.ts

### System / Nuxt Info

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, routeRules
- Runtime Modules:  -
- Build Modules:    -
------------------------------

**Comment by harlan-zw** [comment]
Are you experiencing this outside of StackBlitz? I've noticed their types are sometimes broken

**Comment by jf908** [comment]
I was experiencing this issue outside of StackBlitz but after deleting yarn.lock and redownloading all my dependencies, the error has gone away so I will close this.
