### ISSUE TITLE
How to add description and keywords.

### ISSUE THREAD

**Issue by buditanrim** [harlan-zw/nuxt-simple-sitemap#161]
### Details

Hello, thank you for building this module.

**Situation:** I can't find a way to add keywords to the SEO
<img width="660" alt="image" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/1830184/b09ac1c9-727b-46c6-9b52-5074bf0ef59a">

Question: How can I add keywords using nuxt SEO module?

**Comment by harlan-zw** [comment]
Hi, I think you may have the wrong module, this doesn't handle meta tags.

You probably want something like `useSeoMeta({ keywords: 'foo, bar' })`, although no search engine uses these so not sure why you would bother.
