### ISSUE TITLE
How to properly use sources for dynamic pages routes?

### ISSUE THREAD

**Issue by molul** [harlan-zw/nuxt-simple-sitemap#165]
### **Brief explanation:**
I would like to add some urls that I can generate from a json file to the sitemap.

I'm making a website for an illustrator portfolio, which has some static pages and some dynamic urls for each gallery. The galleries pages have the url "MY_DOMAIN/work/GALLERY_NAME".

The galleries are created from a json file I have in my public folder. Each entry in this json file has the name of the gallery, and each gallery has a folder with images in "/public/galleries/work/GALLERY_NAME", and in "pages" folder I have a file "/work/slug", where the slug is the name of the gallery that I use to get the images from the public folder.

### **The issue:**
Now, I'm trying to figure out how to add the urls to the sitemap. I'm following the guide here without success: https://nuxtseo.com/sitemap/guides/dynamic-urls

### **What I have done so far**
So I created a file /server/api/__sitemap__/urls.ts with this content:

```
import { data } from "~/public/galleries/home/data";

export default defineSitemapEventHandler(() => {
  let ret = [];
  for (let i = 0; i < data.length; i++) {
    ret.push({ loc: "/work/" + data[i], _sitemap: "pages" });
  }
  return ret;
});

```

The endpoint seems to work, because If I go to "MY_DOMAIN/api/__sitemap__/urls" I can see the list of URLS like this:
```
[
  {
    "loc": "/work/picture-book-erase-otra-vez",
    "_sitemap": "pages"
  },
  {
    "loc": "/work/la-foto-perfecta",
    "_sitemap": "pages"
  },
  (...and so on)
]
```

Then in my nuxt.config.ts I have this:

```
export default defineNuxtConfig({
(...some other options)
  modules: ["@nuxt/image", "nuxt-icon", "nuxt-simple-sitemap"],
  sitemap: {
    defaults: {
      changefreq: "daily",
      priority: 1,
      lastmod: new Date(),
    },
    sources: ["/api/__sitemap__/urls"],
  },
});
```

However, when I go to "MY_DOMAIN/sitemap.xml" I only see the static pages. 

I would think that the api endpoint is being ignored, but I don't think so, because while I was coding the function in "/server/api/__sitemap__/urls.ts", I got some error messages from fetching the data from mistakes I made in the code, so it seems to be fetched, just the returned array is ignored by the sitemap generator.

Is there anything I'm missing here?

**Comment by molul** [comment]
Classic: I figured out the solution right after submitting the ticket.

I only had to remove the "_sitemap": "pages" thing from the function. As I only have one sitemap, I only needed to return an array of strings, so the urls.ts ended up like this:

```
import { data } from "~/public/galleries/home/data";

export default defineSitemapEventHandler(() => {
  let ret = [];
  for (let i = 0; i < data.length; i++) {
    ret.push("/work/" + data[i]);
  }
  return ret;
});
```

**Comment by harlan-zw** [comment]
Hey @molul, thanks for the issue.

I've pushed up a fix so that it won't filter the sitemaps even if you provide a `_sitemap` for single sitemap configs.

**Comment by molul** [comment]
Oh, nice. Thank you :) 

I would also suggest adding to the docs (to https://nuxtseo.com/sitemap/guides/dynamic-urls) that the "/api/__sitemap__/urls.ts" file should be created under /server. That must be pretty evident for someone who already knows Nuxt, but I started not long ago and hadn't worked with the /server directory yet.

**Comment by harlan-zw** [comment]
Good point, have updated that as I made that mistake in a couple of spots.
