### ISSUE TITLE
Dynamic urls: auto-detection of locale with prefix, or ability to pinpoint to a specific locale

### ISSUE THREAD

**Issue by tmlmt** [harlan-zw/nuxt-simple-sitemap#167]
This is not a feature-request per se, more a feature which should be there if the module is to really cover i18n situations.

### Clear and concise description of the problem

My case is the following example:
- i18n in `prefix_and_default` strategy
- a catchall page serving nuxt/content pages but the website's not in document-driven mode and the content paths are not the same as real paths, so they are not automatically added to sitemap and must come from a dynamic url endpoint
- these pages are not available in all locales, so I'm manually adding the alternative hrefs in the returned array

Dynamic urls are added to all locale sitemaps. In an i18n case, they should be added to the relevant sitemaps only. 

### Suggested solution

The module could, according to the i18n strategy, automatically recognize the locale corresponding to the `loc` and add the url to the right locale sitemap (e.g. `en-US-sitemap.xml`)

### Alternative

Two alternatives:
- Don't force this automatic recognition, but make it optional with a new property (e.g. `_i18nDetect`) similar to `_i18nTransform`
- Add a property (e.g. `_locale`) with locale code (e.g. `en`) as value, to pinpoint to which locale sitemap the url should go to

**Comment by harlan-zw** [comment]
So you may have run into some issues previously as `prefix_and_default` wasn't actually supported properly. It's not a great strategy imo, ideally, you want a clear canonical URL.

Nonetheless, I've added proper support for it in v4.1, worth testing the behavior again. If you still have issues are you able to provide a StackBlitz with some code I can look at? Not entirely sure I understand the scope of this issue.

For filtering based on the sitemap, this is supported with the `_sitemap` key (see https://nuxtseo.com/sitemap/guides/multi-sitemaps#extending-app-sources). However, this shouldn't be needed for i18n sitemaps.

**Comment by tmlmt** [comment]
Sorry for not being clear enough :)

In this repro: https://stackblitz.com/edit/github-vty3pl-ahqwzd?file=server%2Fapi%2F__sitemap__%2Fwiki.ts
Observe that if I don't add this `_sitemap` key, the wiki pages end up in all individual sitemaps. 
<img width="451" alt="image" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/10244927/50b6a7cf-a323-47c2-bef3-c04088fde326">

I hadn't seen the `_sitemap` key! It actually corresponds to Alternative #2 in my original post in this thread. I was arguing that when `_i18nTransform` is not `true`, the presence/absence of prefix in the returned url should determine which individual sitemap it should go to. 

That being said, I hadn't seen the `_sitemap` key! It actually corresponds to Alternative #2 in my original post in this thread. Depending on what was the intended behavior of your module, i.e. if you didn't mean to autodetect the target sitemap like this, I am also ready to use the `_sitemap` key. In that case, I believe the existence and use of that key should be repeated in the doc in the Dynamic URL Endpoint page.

**Comment by harlan-zw** [comment]
Got it, this should be fixed in v4.1.1, it should be able to determine the i18n configuration of URLs automatically.

**Comment by harlan-zw** [comment]
You will need to make a couple of changes to your code though, see https://stackblitz.com/edit/github-vty3pl-ooagzx?file=server%2Fapi%2F__sitemap__%2Fwiki.ts

If you provide a `_sitemap` it won't apply the automatic transformations. The `loc` needs to start with a leading slash for the regex to work (should fix this at some point)

**Comment by tmlmt** [comment]
Great, thanks for the fix! Just one thing: I know you don't like that strategy, but with the `prefix_and_default` strategy, shouldn't the default sitemap also contain the non-prefixed version of the url? Example in the Stackblitz you just posted, `en-US-sitemap.xml` (default locale) should also contain `/wiki/page1` and `/wiki/page2` I believe. It seems to be correctly done with nuxt:pages, but not with dynamic urls.

**Comment by tmlmt** [comment]
Awesome auto sitemap determination :) Thanks
