### ISSUE TITLE
When using `Dynamic URL Endpoint`, an error message will be prompted when returning a custom list type, but it does not affect the use

### ISSUE THREAD

**Issue by lxccc812** [harlan-zw/nuxt-simple-sitemap#168]
### Describe the bug

When I return a custom list type in the function `defineSitemapEventHandler`, an error message is prompted, but it does not affect the use.
![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/110974969/cfc3db5b-a066-45bd-91b3-8bf95921afd0)

### Reproduction

none

### System / Nuxt Info

```Shell
nuxt 3.8.1
nuxt-simple-sitemap 4.1.0


nuxt.config.ts
sitemap: {
    xsl: false,
    sources: ['/api/__sitemap__/urls'],
}
```

**Comment by harlan-zw** [comment]
Hi @lxccc812 

If you just want to get the types passing, the easier solution is to replace `SitemapRecord` with `ReturnType<typeof asSitemapUrl>`

```ts
import type { asSitemapUrl } from '#imports'

interface Sitemap {
  sitemaps: ReturnType<typeof asSitemapUrl>
}
```

Just FYI `url` is deprecated, you should use `loc`.

Will close for now but let me know if you need more help.
