### ISSUE TITLE
multiple sitemaps and i18n

### ISSUE THREAD

**Issue by djixadin** [harlan-zw/nuxt-simple-sitemap#169]
### Details

not sure if im correct but this feels like a regression. i didn't have this problem on v3.. with 4.1 it seems to be the issue.
im using 
```
@nuxtjs/i18n": "^8.0.0-rc.5
@nuxtseo/module": "^2.0.0-beta.42

```

my 1i8n config file:

```
    types: 'composition',
    customRoutes: 'config',
    locales: [{ code: locale, file: `${market}.json` }],
    defaultLocale: locale,
    strategy: 'prefix_except_default',
    lazy: true,
    langDir: 'translations',
```

now i have pages where i have false set for certain links but those pages and all of the other localization are included in the sitemap and that was not the case before.. maybe im missing something from the new docs.. to clarify again im only having problems with the static pages that are found in nuxt pages pages. i implemented dynamic links without any problem

**Comment by harlan-zw** [comment]
Can you full proper code/reproduction, it's not clear what you mean by 

> now i have pages where i have false set for certain links 

 There's an i18n Stackblitz starter here https://stackblitz.com/edit/nuxt-starter-jwuie4?file=package.json

**Comment by djixadin** [comment]
https://stackblitz.com/edit/nuxt-starter-qfuzg8?file=nuxt.config.ts,pages%2Findex.vue

in both of sitemaps you have both links and it makes more sense to have one right?

**Comment by harlan-zw** [comment]
Thanks @djixadin, this is something I missed and was fixed in https://github.com/harlan-zw/nuxt-simple-sitemap/commit/87c7342, please try v4.1.1
