### ISSUE TITLE
`include` option not working with multiple sitemaps

### ISSUE THREAD

**Issue by NtchPlayer** [harlan-zw/nuxt-simple-sitemap#170]
### Describe the bug

The `include` options didn't work when it use in `sitemaps` options to manage multiples sitemap.

As you can see in `nuxt.config.ts`, I set sitemaps options like that:

```JS
sitemap: {
  sitemaps: {
    main: {
      includeAppSources: true,
      include: ['/fr', '/en', '/fr/about', '/en/about'],
    },
  },
}
```

But on url `/main-sitemap.xml`, `/about` page is not added to the sitemap-main. There is only root page for each language.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-doetn4?file=nuxt.config.ts

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      modules, i18n, site, sitemap
- Runtime Modules:  nuxt-simple-sitemap@4.1.2, @nuxtjs/i18n@8.0.0-rc.5
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Thanks for the detailed issue. Have pushed up a fix.

**Comment by NtchPlayer** [comment]
Thx for you reactivity !

**Comment by NtchPlayer** [comment]
It's just implement it now and it's work perfectly ! And I see that, now you add prefix automatically on include and exclude url !

So we can define it like that:`include: ['/auth/**', '/search/', '/privacy-policy', '/']` :D Thx again !
