### ISSUE TITLE
Option site.url not used in Canonical URL

### ISSUE THREAD

**Issue by FBerthelot** [harlan-zw/nuxt-simple-sitemap#171]
### Describe the bug

Hello,

First of all, your next-simple-* seo modules are great, thank you for them :)

I'm stuck at setting a different URL than `http://localhost:3000` with this module.

The createSitePathResolver seams to not care about nuxt config `site.url` option.
https://github.com/harlan-zw/nuxt-simple-sitemap/blob/main/src/runtime/routes/sitemap_index.xml.ts#L10C27-L10C49

I cannot find where the createSitePathResolver come from so I cannot do a PR to fix the code (or improve the documentation if I miss something).

Thanks :)

### Reproduction

Here are the steps to reproduce:

- Go here (the example from documentation), https://stackblitz.com/edit/nuxt-starter-dyraxc?file=nuxt.config.ts
- Click on the sitemap.xml in the right panel. As you can see, URL is starting with `http://localhost:3000`.
- In the nuxt.config, you can see `site.url` is set to `http://nuxtseo.com`.
- ❌ URL should start with `http://nuxtseo.com` and not `http://localhost:3000`.

**Comment by harlan-zw** [comment]
Hi @FBerthelot, thank you for the kind words.

Can you confirm whether this is something you're experiencing in production or just development?

In development the Nitro host is used, this is so you can click through the sitemap links for easier debugging. This is explained in the right-hand panel

![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/5326365/449c8016-f432-4669-96a7-e437263015c2)

If you click the canonical link (in a non-stackblitz environment, the host isn't properly accessible) it will show the sitemap with the canonical displayed instead.

**Comment by FBerthelot** [comment]
I forgot to say I use Static Site Generation (`nuxt generate`) in production.

Even with a NODE_ENV=production, I still have localhost in the sitemap.

**Comment by harlan-zw** [comment]
Did you set a `site.url` per the [documentation](https://nuxtseo.com/sitemap/getting-started/installation)?

**Comment by FBerthelot** [comment]
Yes of course :)

**Comment by FBerthelot** [comment]
After closer look into the stackblitz, I see it's working well with `nuxt generate`. 🤔 

<img width="484" alt="Capture d’écran 2023-11-16 à 01 19 49" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/6927852/36a6ed2b-1a86-4fd6-a5bd-db297a8f2530">


So I don't know what's wrong with my project 🤷‍♂️
My config look like this :
```js
export default defineNuxtConfig({
  devServer: {
    port: 5000,
  },
  ssr: true,

  site: {
    url: 'https://berthelot.io',
  },
  /** ... **/
  modules: [
    '@nuxtjs/i18n',
    '@nuxt/content',
    'nuxt-simple-robots',
    'nuxt-simple-sitemap',
  ]
})
```

**Comment by harlan-zw** [comment]
If you've set a `baseUrl` you'll need to make sure it matches the site.url

**Comment by FBerthelot** [comment]
You are right !!!!!!

Thank you so much ! I've spend too many hours on this issue 🤦 
`i18n.baseUrl` was set via a environnement variable so I haven't seen it...

Many thanks ❤️
