### ISSUE TITLE
[Doc] Inconsistent `autoLastmod` default value

### ISSUE THREAD

**Issue by toto6038** [harlan-zw/nuxt-simple-sitemap#176]
### Describe the bug

As https://github.com/harlan-zw/nuxt-simple-sitemap/issues/146#issuecomment-1807414846 indicates that `autoLastmod` is defaulting to `false` since 4.1, the corresponding description in [documentation](https://nuxtseo.com/sitemap/api/config#autolastmod) seems to be outdated.

<img width="726" alt="image" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/50100922/7e3d5d26-dd27-410f-88c6-fb7cbc43faac">

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v18.18.2`
- Nuxt Version:     `3.8.1`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.7.2`
- Package Manager:  `pnpm@8.10.2`
- Builder:          `-`
- User Config:      `css`, `devtools`, `modules`, `imports`, `postcss`, `gtm`, `security`, `runtimeConfig`, `routeRules`, `sitemap`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.9.4`, `@pinia/nuxt@0.5.1`, `@nuxt/image@1.0.0-rc.1`, `@vueuse/nuxt@10.6.1`, `nuxt-lodash@2.5.3`, `nuxt-security@0.14.4`, `@zadigetvoltaire/nuxt-gtm@0.0.13`, `@nuxt/content@2.9.0`, `@vueuse/nuxt@10.6.1`, `nuxt-simple-sitemap@4.1.7`
- Build Modules:    `-`
```

**Comment by harlan-zw** [comment]
Thanks! Have fixed that in the docs and in the code docs.
