### ISSUE TITLE
Nuxt Build Error: The requested module 'node:module' does not provide an export named 'isBuiltin'

### ISSUE THREAD

**Issue by Semion120** [harlan-zw/nuxt-simple-sitemap#178]
### Describe the bug

Hi. I have some problem. 

I have nuxt 3.8.2. Everything works well on the local machine, but when I install it on vps an error appears. The only thing I did that caused an error was to install Nuxt Simple Sitemap. Only on static site generation.

I looked for a solution, but all the suggestions did not help: I ​​changed node versions, deleted the yarn.lock file, updated all packages using yarn upgrade. Maybe someone encountered an error?

Full error text:
 ERROR  Nuxt Build Error: The requested module 'node:module' does not provide an export named 'isBuiltin'                                                          2:23:53 PM

  import { isBuiltin } from 'node:module';
  ^^^^^^^^^
  SyntaxError: The requested module 'node:module' does not provide an export named 'isBuiltin'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async bundle (node_modules/nuxt/dist/index.mjs:4512:76)
  at async Promise.all (index 1)
  at async build (node_modules/nuxt/dist/index.mjs:4388:5)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:98:5)
  at async Object.run (node_modules/nuxi/dist/chunks/generate.mjs:59:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 

package.json:
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev --port 3005",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "lint:js": "eslint --ext \".ts,.vue\" --ignore-path .gitignore .",
    "lint:prettier": "prettier --check .",
    "lint": "yarn lint:js && yarn lint:prettier",
    "lintfix": "prettier --write --list-different . && yarn lint:js --fix"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@typescript-eslint/parser": "^6.4.1",
    "eslint": "^8.48.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "nuxt": "^3.7.0",
    "nuxt-simple-sitemap": "^4.1.7",
    "prettier": "^3.0.2",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "@nuxt/image": "^1.0.0-rc.3",
    "@pinia/nuxt": "^0.4.11",
    "pinia": "^2.1.6",
    "sass": "^1.69.5",
    "sass-loader": "^13.3.2",
    "vue3-carousel-nuxt": "^1.1.0"
  }
}

nuxt.config:
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  ssr: true,
  $production: {
    routeRules: {
      "/**": { isr: true },
    },
  },
  $development: {
    routeRules: {
      "/**": { isr: true },
    },
  },
  nitro: {
    prerender: {
      crawlLinks: true,
      failOnError: false,
    },
  },
  css: ["~/assets/css/reset.css", "~/assets/css/main.css"],
  modules: [
    "nuxt-simple-sitemap",
    "@pinia/nuxt",
    "@nuxt/image",
    "vue3-carousel-nuxt",
  ],
  carousel: {
    prefix: "First",
  },
  site: {
    url: "https://site.com",
  },
});

### Reproduction

Error immediately after installing Nuxt Simple Sitemap. When generating a site statically

### System / Nuxt Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Xeon(R) Gold 6240R CPU @ 2.40GHz
    Memory: 1.01 GB / 1.92 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
```

**Comment by harlan-zw** [comment]
Please see here https://github.com/nuxt/nuxt/issues/24402

**Comment by Semion120** [comment]
yeap, I did everything from this issue nuxt/nuxt/issues/24402. Its't help in my case
