### ISSUE TITLE
exclude using regex not working

### ISSUE THREAD

**Issue by doktor-meirer** [harlan-zw/nuxt-simple-sitemap#184]
### Describe the bug

i'm trying to hide pages using regex (which should be possible as mentioned in [docs](https://nuxtseo.com/sitemap/guides/filtering-urls).

this does not seem to work for a page called `hide-me.vue`:
```js
  sitemap: {
    exclude: [/.*hide-me.*/],
  }
```

am i missing something or is this a bug?

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zqvdmm?file=nuxt.config.ts

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, modules, nitro, site, sitemap
- Runtime Modules:  nuxt-simple-sitemap@4.1.9
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
@PabloGBarcelo' has pushed up a fix that is available in `v4.1.11`.

Let us know if you have any issues with it :)

**Comment by codeflorist** [comment]
@PabloGBarcelo @harlan-zw 

many thanks for the fix you two!

this might be a bit of an edge case, but strangely it doesn't seem to work, if the `site.url` includes a `#` character. e.g.:
```js
  site: {
    url: 'https://site.url#foo',
  },
```

here is an updated reproduction:
https://stackblitz.com/edit/nuxt-starter-zqvdmm?file=nuxt.config.ts

if you remove `#foo` from the `site.url` the exclude is working.

**Comment by harlan-zw** [comment]
Uh yes I'd avoid putting a hash in your site URL, this is meant to be the canonical site URL :grimacing:

I've made an issue here to track as the module should normalize the hash away https://github.com/harlan-zw/nuxt-site-config/issues/13
