### ISSUE TITLE
`lastmod` automatic conversion to date format recognized by Google crawler failed

### ISSUE THREAD

**Issue by lxccc812** [harlan-zw/nuxt-simple-sitemap#193]
### Describe the bug

Google's crawler cannot parse date and time strings containing milliseconds, so when I return a date in this format of `2023-12-21T13:49:27.963745`, Google's crawler fails to parse `lastmod` correctly.

However, as early as version 3.4.0, lastmod can be automatically converted into the `2023-12-21T13:49:27+00:00` format that can be parsed. Are there any major changes in this regard in version 4.0?

Using the example in dynamic url in `nuxt-simple-sitemap@3.4.0`, the lastmod format is automatically converted
![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/110974969/e30de5b0-a525-4e41-8ea3-93778e8e61e8)

### System / Nuxt Info

```shell
------------------------------
- Operating System: Windows_NT
- Node Version:     v16.19.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      modules, ssr, runtimeConfig, app, css, devServer, devtools, device, experimental, gtm, nitro, pwa, site, sitemap
- Runtime Modules:  nuxt-swiper@1.2.2, @unocss/nuxt@0.57.7, @vueuse/nuxt@10.7.0, @nuxtjs/device@3.1.1, @vite-pwa/nuxt@0.1.2, nuxt-simple-sitemap@4.2.0, @zadigetvoltaire/nuxt-gtm@0.0.13
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Hi @lxccc812, thanks for the issue.

I've pushed up a fix for this that will be released shortly. I think it got removed by accident with the refactoring.
