### ISSUE TITLE
How to add images

### ISSUE THREAD

**Issue by liaow-ww** [harlan-zw/nuxt-simple-sitemap#195]
### Details

nuxt: 3.6.5
nuxt-simple-sitemap: 3.2.0

I need to make a sitemap-images, similar to 
https://developers.google.cn/search/docs/crawling-indexing/sitemaps/image-sitemaps?authuser=0&skip_cache=true
, but I didn’t find the setting guide.

I have configured a normal sitemap and localhost:3000/sitemap.xml works fine.

I tried using the configuration in the guide, but it didn't work.

 nuxt.config.ts
```ts
export default defineNuxtConfig({
  sitemap: {
    sitemaps: {
      posts: {
        sources: [
          '/api/sitemap-urls'
        ]
      },
    },
  },
})
```
/api/siemap-urls.ts
```ts
export default defineSitemapEventHandler(() => {
  return [
    {
        loc: '/about',
        lastmod: '2023-02-21T08:50:52.000Z',
        images: [
          {
            loc: 'https://example.com/image.jpg',
          },
        ],
    }
  ]
})
```

**Comment by harlan-zw** [comment]
Hi, you just add the images to the entry. For example:

```ts
{
            loc: '/about',
            lastmod: '2023-02-21T08:50:52.000Z',
            images: [
              {
                loc: 'https://example.com/image.jpg',
              },
            ],
}
```

I'll keep this issue open as a reminder to add docs for it.

**Comment by dany68** [comment]
Hi,
Is it possible to make it auto import all the images from the page ?
Notably with nuxt-content (for blog posts) ?

Thank you for the module

**Comment by liaow-ww** [comment]
> Hi, you just add the images to the entry. For example:
> 
> ```ts
> {
>             loc: '/about',
>             lastmod: '2023-02-21T08:50:52.000Z',
>             images: [
>               {
>                 loc: 'https://example.com/image.jpg',
>               },
>             ],
> }
> ```
> 
> I'll keep this issue open as a reminder to add docs for it.

I'm sorry, Still doesn't work, I added it to sitemap-url.ts

**Comment by harlan-zw** [comment]
Can you provide a reproduction? You can start with https://stackblitz.com/edit/nuxt-starter-dyraxc?file=server%2Fapi%2F_sitemap-urls.ts

**Comment by liaow-ww** [comment]
> ```ts
> posts: {
>         sources: [
>           '/api/sitemap-urls'
>         ]
>       },
> ```

https://stackblitz.com/edit/nuxt-starter-zfejln?file=nuxt.config.ts

**Comment by liaow-ww** [comment]
> Can you provide a reproduction? You can start with https://stackblitz.com/edit/nuxt-starter-dyraxc?file=server%2Fapi%2F_sitemap-urls.ts

https://stackblitz.com/edit/nuxt-starter-zfejln?file=nuxt.config.ts
I don't know if nuxt-simple-sitemap3 is not supported.

**Comment by harlan-zw** [comment]
Looks correct to me? Am I missing something?

``xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/__sitemap__/style.xsl"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>http://localhost:3000/aaa</loc>
        <lastmod>2023-02-21T08:50:52</lastmod>
        <image:image>
            <image:loc>https://example.com/image.jpg</image:loc>
        </image:image>
    </url>
</urlset>

```

**Comment by liaow-ww** [comment]
> Looks correct to me? Am I missing something?
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/__sitemap__/style.xsl"?>
> <urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
>     <url>
>         <loc>http://localhost:3000/aaa</loc>
>         <lastmod>2023-02-21T08:50:52</lastmod>
>         <image:image>
>             <image:loc>https://example.com/image.jpg</image:loc>
>         </image:image>
>     </url>
> </urlset>
> 
> ```

Yes that's correct, I got it I should ctrl+u to view instead of accessing sitemap-images.xml directly.
Thanks a lot for solving my problem!! Now I need to solve the plugin dependency issue.

**Comment by harlan-zw** [comment]
I've added a hint to the side panel to view the page source to see the raw XML, I've also added a docs page for images https://nuxtseo.com/sitemap/guides/images-videos
