### ISSUE TITLE
How to setting sitemap.xml path?

### ISSUE THREAD

**Issue by Nationalcat** [harlan-zw/nuxt-simple-sitemap#197]
As the title suggests, I want to hide sitemaps because I don't want to expose how many records I have.

Maybe add `sitemapPrefix` to support the multiple sitemaps option.

```js
sitemap: {
    sitemapPrefix: '/go/to',
    sitemaps: {
      posts: {
         // ...
      },
      pages: {
        // ...
      },
    },
  }
```

result:
```
https://127.0.0.0/go/to/sitemap_index.xml
```

**Comment by harlan-zw** [comment]
I don't think this is something that will be supported as hiding the amount of records you have is redundant, anyone can query google to see how many indexed URLs exist for a particular domain.

There is a workaround though, if you just use the single sitemap entry you can name it whatever you want with the `sitemapName` option.
