### ISSUE TITLE
Maybe should use `callHook` instead of `hook`

### ISSUE THREAD

**Issue by DanSnow** [harlan-zw/nuxt-simple-sitemap#2]
I guess here is for allowing other modules to modify the sitemap. So here probably should be call hook
https://github.com/harlan-zw/nuxt-simple-sitemap/blob/79807da608df89d2765bf891254baf97414660d1/src/module.ts#LL129C9-L129C66

**Comment by harlan-zw** [comment]
Hey! Thanks for the issue, my bad.

Have pushed up [fix](https://github.com/harlan-zw/nuxt-simple-sitemap/commit/0dbb235d8cef0aa0668a71865bb20a4a054a2c5e) for it
