### ISSUE TITLE
Add opt-out for XML stylesheet

### ISSUE THREAD

**Issue by AnzhiZhang** [harlan-zw/nuxt-simple-sitemap#22]
### Details

Is there any option to set sitemap as a xml file? I would like to use real XML in production.

Can you provide or is there an option to use non styled sitemap in production?

**Comment by harlan-zw** [comment]
Hey @AnzhiZhang, thanks for the issue.

The sitemap is a real XML and is compliant to what Google requires. Feel free to run it through a validator.

I think adding an option to opt out of the XML stylesheet is a good idea though.

**Comment by harlan-zw** [comment]
This is now supported in version 2.2.0.

```ts
sitemap: {
  xsl: false,
}
```

You can also set it to a string if you want to specify your own stylesheet.
