### ISSUE TITLE
hreflang="[object Object]" using i18n and SSG

### ISSUE THREAD

**Issue by Kobreros** [harlan-zw/nuxt-simple-sitemap#26]
### Describe the bug

Attribute in sitemap.xml contains `hreflang="[object Object]"` instead of language code.
The same problem with links but sitemap also contains unnecessary lang subdirectory for lang route.

`<url>`
        `<loc>https://some-host-name</loc>`
        `<lastmod>2023-04-05T22:59:06+00:00</lastmod>`
        `<xhtml:link rel="alternate" hreflang="[object Object]" href="https://some-host-name/%5Bobject%20Object%5D" />`
        `<xhtml:link rel="alternate" hreflang="[object Object]" href="https://some-host-name/%5Bobject%20Object%5D" />`
    `</url>`
    `<url>`
        `<loc>https://some-host-name/en</loc>`
        `<xhtml:link rel="alternate" hreflang="[object Object]" href="https://some-host-name/%5Bobject%20Object%5D/en" />`
        `<xhtml:link rel="alternate" hreflang="[object Object]" href="https://some-host-name/%5Bobject%20Object%5D/en" />`
    `</url>`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-izjkhm

### System / Nuxt Info

```Shell
"nuxt": "^3.3.3",
"@nuxtjs/i18n": "^8.0.0-beta.8",
"nuxt-simple-sitemap": "^2.4.3"

Binaries:
 Node: 18.12.1
 npm: 9.1.2.
```

**Comment by harlan-zw** [comment]
Hey @Kobreros, thanks for the issue.

The fix for the issue here is available in 2.4.4, I actually fixed it a few days ago but forgot to release it.

I've also just pushed support for the `i18n.pages` config in 2.4.5

Let me know if you have any issues with either.
