### ISSUE TITLE
Module not getting pre-rendered routes with Netlify 

### ISSUE THREAD

**Issue by provok-it** [harlan-zw/nuxt-simple-sitemap#28]
### Describe the bug

The module only generates static routes when deployed on Netlify, not the pre-rendered ones.

It works fine in a local environment, though.

You may need to add a base dir when calling `$fetch` on line 100 of `src/runtime/util/entries.ts`:
`prerenderedRoutesPayload = await $fetch('/__sitemap__/routes.json')`

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v19.7.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `modules`, `generateSvgsViewboxes`, `i18n`, `svgo`, `image`, `robots`, `sitemap`, `feed`, `runtimeConfig`, `vue`, `vite`, `nitro`, `routeRules`, `css`, `app`
- Runtime Modules:  `~~/modules/download-global/index.ts`, `~~/modules/download-routes-params/index.ts`, `~~/modules/cms-redirections/index.ts`, `~~/modules/generate-svgs-viewboxes/index.ts`, `~~/modules/lite-youtube-embed/index.ts`, `~~/modules/feed/index.ts`, `@nuxtjs/i18n@8.0.0-beta.10`, `nuxt-svgo@1.1.0`, `@nuxt/image-edge@1.0.0-28008586.381b906`, `nuxt-simple-robots@2.1.1`, `nuxt-simple-sitemap@2.4.3`
- Build Modules:    `-`
```

**Comment by provok-it** [comment]
Hi @harlan-zw ✌️

Your patch is not working.

### Netlify build
<img width="1045" alt="Capture d’écran 2023-04-08 à 12 21 52" src="https://user-images.githubusercontent.com/37068300/230716263-016c9c59-e46c-4d74-8f33-b5d21a53f132.png">


### Local build
<img width="1063" alt="Capture d’écran 2023-04-08 à 12 21 37" src="https://user-images.githubusercontent.com/37068300/230716275-0625c53f-d28b-46dd-b3fb-5c467c708a44.png">

### nuxt-simple-sitemap config
```js
{
  trailingSlash: true,
  inferStaticPagesAsRoutes: false,
}
```

### System / Nuxt Info
```
- Operating System: `Darwin`
- Node Version:     `v19.7.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `modules`, `generateSvgsViewboxes`, `i18n`, `svgo`, `image`, `robots`, `sitemap`, `feed`, `runtimeConfig`, `vue`, `vite`, `nitro`, `routeRules`, `css`, `app`
- Runtime Modules:  `~~/modules/download-global/index.ts`, `~~/modules/download-routes-params/index.ts`, `~~/modules/cms-redirections/index.ts`, `~~/modules/generate-svgs-viewboxes/index.ts`, `~~/modules/lite-youtube-embed/index.ts`, `~~/modules/feed/index.ts`, `@nuxtjs/i18n@8.0.0-beta.10`, `nuxt-svgo@1.1.0`, `@nuxt/image-edge@1.0.0-28008586.381b906`, `nuxt-simple-robots@2.1.1`, `nuxt-simple-sitemap@2.4.7`
- Build Modules:    `-`
```

**Comment by harlan-zw** [comment]
Hi @provok-it 

The fix I deployed was related to the base urls. Would you mind clarifying what the issue is in the screenshot?

It's using `localhost` in production?

**Comment by provok-it** [comment]
First, since your patch `inferStaticPagesAsRoutes: false` seems to have stopped working.

As you can see, the module generates urls that don't exist and corresponds to the name of the files in my `./pages` directory.

![Capture d’écran 2023-04-08 à 15 18 52](https://user-images.githubusercontent.com/37068300/230723343-ee3ddddc-7818-4781-bda4-6e393379ffac.png)

Behind that, the real issue in itself is that in local, all the pre-rendered urls are generated in the sitemap.xml, whereas when deployed on the Netlify preprod and prod the pre-rendered urls are not generated.

It looks like the `prerenderedRoutesPayload` variable used in the file `src/runtime/util/entries.ts` is not filled with the pre-rendered urls when deployed on Netlify.

Of course, it is just a guess.

**Comment by harlan-zw** [comment]
I think the issue is related to the i18n integration and the fact that nitro is using a local fetch for the routes file.

I've pushed up 2 fixes which hopefully these out.

Can you try v2.4.8 and let me know how it goes?

**Comment by provok-it** [comment]
It's working!

Thanks a lot 🙏
