### ISSUE TITLE
Releases version

### ISSUE THREAD

**Issue by botmaster** [harlan-zw/nuxt-simple-sitemap#36]
### Details

Hello [harlan-zw](https://github.com/harlan-zw).
I don't really understand the version management on this project. Why is there version [v2.4.12](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v2.4.12) and version [v1.0.10](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v1.0.10). By the way, v1.0.10 is tagged as the last version.

**Comment by harlan-zw** [comment]
Thanks for the issue! I did miss this, I'll need to figure out a separate dist tag for v1. For now 2.4.13 should be the latest

**Comment by harlan-zw** [comment]
1.x is now released under the `legacy` tag :)

**Comment by botmaster** [comment]
Thanks harlan-zw!
