### ISSUE TITLE
Sitemap 404 no found when deploying to Firebase Hosting

### ISSUE THREAD

**Issue by timotheeduran** [harlan-zw/nuxt-simple-sitemap#39]
### Describe the bug

When using Nitro with `preset: node-server`, the sitemap is accessible via `/sitemap.xml.` However, when using `preset:firebase` and publishing to Firebase Hosting, trying to access `/sitemap.xml` returns a 404 error.

Before going deeper in implementing a reproduction, I wanted to know if this is an expected behavior or if I should use a different configuration.

Thank you! :)

### System / Nuxt Info
"nuxt-simple-sitemap": "^2.4.14"

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 65.20 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 112.1.50.121
    Chrome: 112.0.5615.137
    Safari: 16.3

**Comment by harlan-zw** [comment]
Hey @timotheeduran, thanks for the issue.

This does indeed sound like a bug. Could you confirm if you're using `nuxi generate` or `nuxi build`?

There may be a work around if you prerender your sitemap, otherwise will need to investigate Firebase (haven't used before).

**Comment by timotheeduran** [comment]
Hi! Thanks for your reply.

We are using `NITRO_PRESET=firebase npm run build` and **not** `nuxi generate` or `nuxi build` as described in [the Nuxt3 documentation](https://nitro.unjs.io/deploy/providers/firebase). Then we use `export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json` to deploy to Firebase. That's it.

Let me know if you want me to perform some tests.

**Comment by qtipee** [comment]
> I see. That's quite strange as the `sitemap.xml` endpoint is server handled so shouldn't ever 404.
> 
> Can you just double-check that the latest version 2.4.22 is also broken

Hello, it seems to work with the 2.4.22 version!

I used the `NITRO_PRESET=firebase npm run build` command and it generated the sitemap in local and it also generated it in our Github CI :)
