### ISSUE TITLE
Add hreflang hints to xml stylesheet

### ISSUE THREAD

**Issue by botmaster** [harlan-zw/nuxt-simple-sitemap#41]
### Clear and concise description of the problem

Hello.

No `hreflang` alternatives displayed in the rendered sitemap.xml.

![CleanShot 2023-05-03 at 16 21 01](https://user-images.githubusercontent.com/488208/235944463-cad7b856-79e4-4df6-9245-e2ebb3fb7fd2.png)

### Suggested solution

Maybe we should add a table that would contain the "hreflang" list?

**Comment by harlan-zw** [comment]
Hi @botmaster, thanks for the issue.

Just to confirm, the alternatives are working for you correctly (view source of the sitemap), you would just like to see them within the sitemap stylesheet?

**Comment by botmaster** [comment]
Yes, everything works fine 👏
I would just like to see them within the sitemap stylesheet 🙏.

Sorry, I don't speak English very well

**Comment by mradenkovic** [comment]
Hi @harlan-zw  have the same issue with nuxt 3.5 and i18n not working!! I already disabled the style and in the source as well not shown. Really important.

my source: 
    ```
   ['nuxt-simple-sitemap', {
           xsl: false,
           siteUrl: 'https://hidden',
           sitemaps: false,
           trailingSlash: true,
           autoLastmod: true,
           alternatives: true,
           pages: {
                exclude: [
                    '/store/bag',
                ],
            },
           index: [
               { sitemap: 'https://hidden/sitemap-products.xml' }
           ]
       }]
```

**Comment by harlan-zw** [comment]
> Hi @harlan-zw have the same issue with nuxt 3.5 and i18n not working!! I already disabled the style and in the source as well not shown. Really important.
> 
> my source: ``` ['nuxt-simple-sitemap', { xsl: false, siteUrl: 'https://hidden', sitemaps: false, trailingSlash: true, autoLastmod: true, alternatives: true, pages: { exclude: [ '/store/bag', ], }, index: [ { sitemap: 'https://hidden/sitemap-products.xml' } ] }]

Hi @mradenkovic, you're posting on an unrelated issue. Can you please make a new issue with more details? Ideally a StackBlitz of the problem.

One quick thing I'll say is that your config does not seem to be correct. `pages` and `alternatives` are not valid root keys.

**Comment by mradenkovic** [comment]
@harlan-zw yes i know, i just tried it out if it works before i open a issue

**Comment by harlan-zw** [comment]
Will track here: https://github.com/harlan-zw/nuxt-simple-sitemap/issues/81
