### ISSUE TITLE
How can i make it work with Nuxt Content v2 ?

### ISSUE THREAD

**Issue by furkanavc** [harlan-zw/nuxt-simple-sitemap#43]
### Details

![image](https://user-images.githubusercontent.com/91663671/236166232-5034849a-063d-441d-b04a-a4ffe3e10405.png)
![image](https://user-images.githubusercontent.com/91663671/236166323-187bc420-45fc-41e0-8a10-c853fed11649.png)
i can't make it work can someone help me or if guys have any working example ?
Thank you 
I'm using "nuxt-simple-sitemap": "^2.4.22",

**Comment by harlan-zw** [comment]
Hey @furkanavc. You can should use the ` serverQueryContent` util like so:

```ts
const docs = await serverQueryContent(event).find()
return docs.map(d => ({
   loc: '/news/' + d._path // might be something other than _path
}))
```

You can see an example on fetching the data here: https://content.nuxtjs.org/guide/recipes/sitemap

**Comment by harlan-zw** [comment]
I can look at making this easier, the module would just need to have an idea on your route mapping

**Comment by furkanavc** [comment]
@harlan-zw  Thank you for the help :)
https://stackblitz.com/edit/nuxt-starter-dwj6e5?file=server%2Fapi%2F_sitemap-urls.ts
this works perfect
