### ISSUE TITLE
sitemaps are not taking any effect

### ISSUE THREAD

**Issue by kirtan403** [harlan-zw/nuxt-simple-sitemap#49]
### Describe the bug

Tried to create multiple sitemaps with the following code in the nuxt config:

```
sitemap: {
    // manually chunk into multiple sitemaps
    sitemaps: {
      posts: {
        include: [
          '/blog/**',
        ],
        // example: give blog posts slightly higher priority (this is optional)
        defaults: { priority: 0.7 },
      },
      pages: {
        exclude: [
          '/blog/**',
        ]
      },
    },
  },
```

This is not making any difference. It is by default generating the default sitemap. Even If remove the above config, no changes in the sitemap generated. 

I'm generating the static build with `npm run generate`.

Btw, I'm using `nuxt-seo-kit` for the sitemap generation.

### System / Nuxt Info

```Shell
Nuxt: v3.3.1

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 2.02 GB / 15.84 GB
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.22621.1
```

**Comment by lisaschumann** [comment]
@kirtan403 For me it worked without using a "post" or "page" object, like this:
```
    sitemap: {
      siteUrl: 'https://yourdomain.com',
        include: [
          '/blog/**',
        ],
      exclude: [
          '/tools/**',
          '/about/**',
      ],
    },
```
If I omit the include array altogether it will list all pages excluding the excluded pages. If I specify the included pages, it will only show the included pages.

**Comment by harlan-zw** [comment]
You may want to check which version of nuxt-simple-sitemap you're using, the nuxt-seo-kit versions is using 1.x. The v2 for nuxt-seo-kit is being worked on which bumps all these dependencies.
