### ISSUE TITLE
[Feature Request] Ability to add `lastmod` to`sitemap.defaults` or to the `routeRules`

### ISSUE THREAD

**Issue by madebyfabian** [harlan-zw/nuxt-simple-sitemap#5]
### Clear and concise description of the problem

I am currrently moving a small project from nuxt 2 -> nuxt 3 and saw that the @nuxtjs/sitemap module is not maintained. So I moved over to this and everything works fine. Except, I had a lastmod date default in my config, to add this date to all entries.

I could not find a way to archive this in this module. Maybe this is by design, and the lastmod date is not required for sitemaps. If so, I'll add a PR to the docs of this module to point this out.

If you think this option is also useful, I can submit a PR for it.

### Suggested solution

- I tried to apply it to the `sitemap` option, but the`sitemap.defaults` option is not available.
```
sitemap: {
    hostname: "https://example.com",
    defaults: { lastmod: new Date() },
}
```

- I tried to apply it to the routeRules, but this option is also not available.
```
routeRules: {
  '/': { sitemap: { changefreq: 'weekly', priority: 1, lastmod: new Date() } },
},
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by harlan-zw** [comment]
Hey @madebyfabian 

Thanks for the issue! A great suggestion. I believe this was already supported, just the types hadn't been set up.

Can you upgrade to [v1](https://github.com/harlan-zw/nuxt-simple-sitemap/issues/5) and let me know how it goes.

You might need to set up the route rule as

```ts
  '/about': {
      sitemap: {
        lastmod: new Date().toString(),
        changefreq: 'daily',
        priority: 0.3
      }
    },
```

**Comment by madebyfabian** [comment]
@harlan-zw Works like a charm! Upgraded and added the option. Thank you!
