### ISSUE TITLE
Generating sitemap index - with an external URL

### ISSUE THREAD

**Issue by kirtan403** [harlan-zw/nuxt-simple-sitemap#50]
### Details

We wanted to generate a sitemap index with 2 sitemaps:

1. One sitemap generated by this module.
2. One external sitemap url, which points to one of our site that is hosted on the subpath.

How can we achieve this?

I tried to split this with the `sitemaps` key (https://github.com/harlan-zw/nuxt-simple-sitemap#multiple-sitemap-support), but this doesn't seem to take any effect (https://github.com/harlan-zw/nuxt-simple-sitemap/issues/49).

**Comment by harlan-zw** [comment]
Hi @kirtan403, thanks for the issue :)

This is now supported in v2.6.0 using the `sitemaps.index` key. You can see the docs here: https://github.com/harlan-zw/nuxt-simple-sitemap#manual-chunking

```ts
 sitemaps: {
  // generated sitemaps  
  posts: {
    // ...
  },
  pages: {
    // ...
  },
  // extending the index sitemap with an external sitemap
  index: [
    { sitemap: 'https://www.google.com/sitemap-pages.xml' }
  ]
}
```
