### ISSUE TITLE
Sitemap doesn't work in production without SSL configured server-side

### ISSUE THREAD

**Issue by cbedwell-dev** [harlan-zw/nuxt-simple-sitemap#53]
### Describe the bug

I am running Nuxt within a Docker environment with an Nginx reverse proxy. I do not have a LetsEncrypt certificate or any SSL configured on the reverse proxy, since it is handled by my load balancer in AWS. When I navigate to [/sitemap.xml](https://staging.eightpoint.ky/sitemap.xml), it is failing with the error:

> request to https://website:8080/__sitemap__/routes.json failed, reason: write EPROTO 139859522480944:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331: (https://website:8080/__sitemap__/routes.json)

The sitemap is failing to fetch the routes.json file, since it is fetching it server-side on an https connection, when in fact there is no SSL on the server. I took a look at the codebase and I believe it is because the host is resolving to my Docker container named 'website', instead of 'localhost' or '127.0.0.1', which sets the useHTTP flag to false. This is probably an edge case that hasn't been considered, but wanted to bring it to your attention in case it is a bug or defect.

**Comment by cbedwell-dev** [comment]
As a temporary fix, I renamed my Docker container to 'localhostsite', so the useHTTP flag isn't set. It's not the best solution but works in the meantime, at least until it is addressed.

**Comment by harlan-zw** [comment]
Hi @cbedwell-dev, previously in `h3` is wasn't using the x-forward headers to resolve the real host. This is fixed in 2.6.0, would you mind seeing if this version works?

**Comment by cbedwell-dev** [comment]
@harlan-zw This works perfect, thank you so much!
