### ISSUE TITLE
Bug i18n and prefix

### ISSUE THREAD

**Issue by benjamin-ret** [harlan-zw/nuxt-simple-sitemap#54]
### Describe the bug

Hi, 

I have problem autogenerating with i18n :

ex, it's generate :
<xhtml:link rel="alternate" hreflang="fr" href="https://google.com/bonjour" />

but prefix fr missing, must be : 
<xhtml:link rel="alternate" hreflang="fr" href="https://google.com/fr/bonjour" />

Thanks

### Reproduction

i18n + differents locales with prefix

### System / Nuxt Info

```Shell
- Operating System: Darwin
- Node Version:     v19.8.1
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.4.0
- Builder:          vite
- User Config:      css, postcss, typescript, plugins, modules, plausible, i18n, build
- Runtime Modules:  @nuxtjs/plausible@0.2.1, @nuxtjs/i18n@8.0.0-beta.9
- Build Modules:    -
```

**Comment by harlan-zw** [comment]
Hi @benjamin-ret, would you mind sharing some reproduction details?

I'll be able to help quickest with a StackBlitz but your nuxt i18n and nuxt simple sitemap config might be enough also.
