### ISSUE TITLE
Sitemap is not working when hosting nuxt app as SSR in AWS Lambda

### ISSUE THREAD

**Issue by anjali89r** [harlan-zw/nuxt-simple-sitemap#55]
### Describe the bug

I'm hosting my nuxt app as SSR in AWS Lambda. When I do the `nuxt build`, the process is generating the `__sitemap__/routes.json` under the public and this is part of the package deployed to the lambda. But when I access the sitemap, it throws this error in the logs and the website return a 404 page.
```
2023-05-20T01:04:09.593Z 9b2aa494-9714-49ba-9c9c-406a52a37d05 WARN [Vue Router warn]: No match found for location with path "/__sitemap__/routes.json"
```
<img width="412" alt="Screen Shot 2023-05-19 at 9 09 00 PM" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/30242582/fe7b51c0-bb79-4fc5-823c-37920792b510">

Attached the lambda package content screenshot from AWS console.

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.5.0`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `sitemap`, `meta`, `nitro`, `server`, `css`, `build`
- Runtime Modules:  `nuxt-simple-sitemap@2.5.0`, `@nuxtjs/tailwindcss@6.7.0`, `@nuxtjs/robots@3.0.0`
- Build Modules:    `-`
```

**Comment by harlan-zw** [comment]
Relates to https://github.com/harlan-zw/nuxt-simple-sitemap/issues/53

**Comment by harlan-zw** [comment]
Thanks for the issue @anjali89r! I will try to look into this when possible.

One issue is that I don't use Lambda for any of my personal sites so it may be a vendor specific issue that will require me to set up infastucture I haven't used before.

Would it be possible to provide more of your nuxt config in the mean time? Would be good to know if you're generating thre sitemap at build time or runtime.

**Comment by anjali89r** [comment]
Sure, here is the nuxt config. I'm generating the site map during the build time.

``` js
export default defineNuxtConfig({

    runtimeConfig: {

        public: {
            apiBase: process.env.NUXT_PUBLIC_API_BASE,

        }
    },
    // ,
    // , 
    modules: ['nuxt-simple-sitemap', '@nuxtjs/tailwindcss', '@nuxtjs/robots'],
    sitemap: {
        siteUrl: 'https://example.com',
        urls: async () => {
            return await getUrls()
        },
    },
    meta: {
        htmlAttrs: {
            lang: 'en',
        },
        charset: 'utf8',
        link: [
            { rel: 'icon', type: 'image/ico', href: '/favicon.ico' },
        ],
        meta: [

            {
                name: 'google-site-verification',
                content:
                    'XXXXXXX',
                hid: 'google-site-verification'
            }],
        script: [
            {
                src: 'https://www.googletagmanager.com/gtag/js?id=UA-XXXXX-1',
                body: false,
                async: true
            }
        ]
    },
    nitro: {
        preset: 'aws-lambda'
    },
    server: {
        host: '0'
    },
    css: ["~/assets/css/tailwind.css"],
    build: {

        transpile: ['@heroicons/vue'],

        postcss: {
            postcssOptions: {
                plugins: {
                    tailwindcss: {},
                    autoprefixer: {},
                },
            },
        },
    }
})
```

I also tested passing the CDN URL(NUXT_APP_CDN_URL) for all my js,css files and sitemap.xml to save in the s3 and that also didn't work. I got the 500 error with the sitemap not available error.

**Comment by anjali89r** [comment]
Also I followed this blog to setup the app in was lambda - https://towardsserverless.com/articles/nuxt3-ssr-on-aws-lambda

**Comment by harlan-zw** [comment]
Hi, is this still an issue? The latest is working on Netlify which uses AWS under the hood so should be okay :thinking:
