### ISSUE TITLE
how to set up? 

### ISSUE THREAD

**Issue by geoHeil** [harlan-zw/nuxt-simple-sitemap#58]
### Describe the bug

I have set up the site map as outlined here  https://stackblitz.com/edit/nuxt-starter-dyraxc?file=package.json, https://github.com/harlan-zw/nuxt-simple-sitemap and also followed this example here: https://github.com/harlan-zw/harlanzw.com/blob/main/server/routes/feed.atom.ts

```
export default defineNuxtConfig({
  extends: ["nuxt-seo-kit"],
  modules: [
    "@nuxtjs/tailwindcss",
    "nuxt-meilisearch",
    "@pinia/nuxt",
    "nuxt-mapbox",
    "@unlighthouse/nuxt",
    "nuxt-jsonld",
    "@nuxtjs/apollo",
  ],
runtimeConfig: {
    public: {
      siteUrl: process.env.NUXT_PUBLIC_SITE_URL || "https://foobar.com",
  },
nitro: {
    serveStatic: true,
    prerender: {
      crawlLinks: true,
      routes: [
        '/',
      ]
    }
  },
  sitemap: {
     sitemaps: true,
     include: [
      '/data/**',
     ],
  },
```

The dynamic configuration should. be sourced from `server/api/_sitemap-urls.ts`:

```
export default cachedEventHandler(
    async (e) => {
      const posts = await Promise.all([
        {
          _path: '/blog/post-a',
          modifiedAt: new Date(),
        },
      ]);
      return posts.map((p) => {
        return {
          loc: p._path,
          lastmod: p.modifiedAt,
        };
      });
    },
    {
      name: 'sitemap-dynamic-url',
      maxAge: 60 * 10, // cache URLs for 10 minutes
    }
  );
```

For now, this is only a dummy dynamic config - but it should be created using a GRAPHQL call in the future using apollo.

## problems

- neither the includes of sites from the `sitemap.include` array are present
- nor the dynamic generated stuff from the event handler

Only the routes (static ones) which are generated by default are created.

### System / Nuxt Info

```Shell
nuxt: 3.5.2
```

**Comment by geoHeil** [comment]
Even the sitemap:prerender hook is ignored.

**Comment by harlan-zw** [comment]
Can you confirm you're depending on the latest version of nuxt-simple-sitemap and not just using the nuxt-seo-kit dependency? Nuxt SEO Kit v1 is on the v1 of nuxt-simple-sitemap. I'm currently working on a v2 to address this

Otherwise a StackBlitz reproduction would be very useful

**Comment by geoHeil** [comment]
@harlan-zw as you reacted with a 👍 please can you ping me here once you have updated the example. Many thanks.

**Comment by willmac997** [comment]
I am quite interested in using GraphQL over REST. @geoHeil Just wondering if you've managed to make any progress on this?

**Comment by geoHeil** [comment]
Currently I resolved the task by creating a python script, collecting all the data (URLs) into a list and then manually copy pasting this into the javascript array. This is certainly not ideal

**Comment by harlan-zw** [comment]
Will track here: https://github.com/harlan-zw/nuxt-simple-sitemap/issues/80
