### ISSUE TITLE
managing sitemap at runtime in swr with data from an headless cms

### ISSUE THREAD

**Issue by Sandros94** [harlan-zw/nuxt-simple-sitemap#59]
### Details

So, as stated in the [nuxt-seo-kit](https://github.com/harlan-zw/nuxt-seo-kit/issues/45) I've noticed that simple-sitemap needs to prerender all the pages so that it could create the sitemap. Quite fine for SSG but not so much when on SSR with SWR and ISR...

So I started studying how [dynamic urls setup](https://github.com/harlan-zw/nuxt-simple-sitemap#handling-dynamic-urls) works, but if I understand it correctly, for the `loc` I should provide the slug and not the full url right? But then where I put the full url? In the `sitemap.siteUrl` inside `nuxt.config.ts`? But if I do so doesn't it reactivate the prerendering?

**Comment by harlan-zw** [comment]
Hey @Sandros94, in the latest version of nuxt-simple-sitemp it reads from the request headers to determine the site URL. You should be able to just leave `siteUrl` undefined if you're generating the sitemap at runtime.

**Comment by Sandros94** [comment]
Thanks, as soon as I manage to list the slugs from my backend and test this I'll update.

**Comment by arjunhadke7** [comment]
> Hey @Sandros94, in the latest version of nuxt-simple-sitemp it reads from the request headers to determine the site URL. You should be able to just leave `siteUrl` undefined if you're generating the sitemap at runtime.

Hi, I added some slugs statically for now (to check if they are added to the sitemap, before fetching them from my CMS) to the code and my code looks like this:

```
export default cachedEventHandler(async () => {
    // const [
    //   posts,
    // ] = await Promise.all([
    //   {
    //     url:'/blog/hello-world',
    //     updatedAt:'8998',
    //   }
    // ])
    // return [posts].map((p) => {
    //   return { loc: p.url, lastmod: p.updatedAt }
    // })
    return [
        {
            loc: 'hello-there', lastMod: '8378787'
        },
        {
            loc: 'hello-world', lastMod: '8378787'
        },
    ]
  }
  , {
    name: 'sitemap-dynamic-urls',
    maxAge: 60 * 10 // cache URLs for 10 minutes
  }
  )
```

I generated a build and I cant see the list of those in the sitemap.xml file. Only the prerendered routes are available.

What must be going wrong? I am new to Nuxt in general.

**Comment by harlan-zw** [comment]
@arjunhadke7 Does it work in dev? If so, what method are you using to build / preview?

**Comment by arjunhadke7** [comment]
> @arjunhadke7 Does it work in dev? If so, what method are you using to build / preview?

No it doesnt show up at all on dev.

**Comment by arjunhadke7** [comment]
@harlan-zw For now I am relying on Start-time dynamic URLs.
This section: https://github.com/harlan-zw/nuxt-simple-sitemap#start-time-dynamic-urls

Since I dont have a lot many posts or pages that are being called from the CMS.

**Comment by harlan-zw** [comment]
Will track this as part of https://github.com/harlan-zw/nuxt-simple-sitemap/issues/80

**Comment by Sandros94** [comment]
> Will track this as part of #80

Sounds good.
Currently I'm still scratching my head around how should I handle this in the backend (not to mention a small bug in the [directus flow](https://github.com/directus/directus/issues/18861)). But we do agree that it is best suited there, since the data handled by the backend and nuxt only creates the interactivity.

**Comment by notflip** [comment]
@Sandros94 I'm also struggling with Directus and this repository, did you find a solution?

**Comment by Sandros94** [comment]
> @Sandros94 I'm also struggling with Directus and this repository, did you find a solution?

Not really, I got offtrack when the new SDK released.

Currently I'm testing stuff around the `nuxt-directus` module and the new SDK. Only then I would have come back to this topic.
