### ISSUE TITLE
Respecting defineI18nRoute of nuxt/i18n

### ISSUE THREAD

**Issue by apsyleg** [harlan-zw/nuxt-simple-sitemap#66]
### Details

Hi! I have a page component where I used [defineI18nRoute](https://v8.i18n.nuxtjs.org/guide/ignoring-localized-routes#pick-localized-routes) to set page available only in few locales, not in all
For example
```
defineI18nRoute({
  locales: ["id", "it"],
});
```
But it seems like nuxt-simple-sitemap still generating rel="alternate" options in sitemap.xml
Is this an expected behavior?

Thanks for cool Nuxt module 👍

**Comment by harlan-zw** [comment]
Hey, thanks for the issue :)

I think this should definitely be supported, unfortunately, it's not straightforward, I'll need to do some digging into how to access the build-time macro data.

Will keep you updated

**Comment by apsyleg** [comment]
Just an idea: maybe we can rely on Vue Router's [getRoutes()](https://v3.router.vuejs.org/api/#router-getroutes) to actually generate sitemap? This list will not contain routes for excluded by defineI18nRoute locales. 
@harlan-zw

**Comment by harlan-zw** [comment]
> Just an idea: maybe we can rely on Vue Router's [getRoutes()](https://v3.router.vuejs.org/api/#router-getroutes) to actually generate sitemap? This list will not contain routes for excluded by defineI18nRoute locales. @harlan-zw

This is only available in a Nuxt app context, which isn't exposed to the nitro handler that serves the sitemap. Also when we prerender we don't have the nitro context either, only a build context. So it's quite limiting, it's why this module has taken a long to develop.

**Comment by apsyleg** [comment]
> This is only available in a Nuxt app context, which isn't exposed to the nitro handler that serves the sitemap. Also when we prerender we don't have the nitro context either, only a build context. So it's quite limiting, it's why this module has taken a long to develop.

Okay, got it. Thank you for explanation!

**Comment by harlan-zw** [comment]
Will track here: [Discordapp.com/channels/@me/649530878254383109](https://github.com/harlan-zw/nuxt-simple-sitemap/issues/82)
