### ISSUE TITLE
loading dynamic urls via external API

### ISSUE THREAD

**Issue by Swidjit** [harlan-zw/nuxt-simple-sitemap#67]
### Details

Hi, I'm wondering if it's possible to load dynamic urls from an external API such as 
sitemap: {
    sitemaps: {
      urls: async () => {
        const gamePages = await $fetch(`${process.env.API_URL}/games`)
        return gamePages.map((page) => ({
          loc: `/games/${page.slug}`,
          lastmod: page.updated_at,
          changefreq: 'daily',
          priority: 0.8,
        }))
      },
    },
  },

**Comment by harlan-zw** [comment]
Hey @Swidjit

Did you see the documentation for [Handling Dynamic URLs](https://github.com/harlan-zw/nuxt-simple-sitemap#handling-dynamic-urls)?

**Comment by Swidjit** [comment]
> Hey @Swidjit
> 
> Did you see the documentation for [Handling Dynamic URLs](https://github.com/harlan-zw/nuxt-simple-sitemap#handling-dynamic-urls)?

yes!  the examples seemed to assume a nuxt server, or something with same url, so i wasn't sure if it would be possible otherwise.  but the code i have above is not working - i get an empty sitemap - even though my api endpoint works fine and provides he expected data.  I'm not sure how to troubleshoot this since Im unsure where to look for errors, or how to test generation locally and see what's going wrong.  Thanks for your quickly reply!

**Comment by Swidjit** [comment]
are you able to show how/where getBlogPages() is defined in the example you give?

**Comment by Swidjit** [comment]
ah I figured it out:
const response = await fetch(${process.env.API_URL}/games)
const gamePages = await response.json()

**Comment by harlan-zw** [comment]
Will keep open until the docs are improved around external fetching

**Comment by mrpalych** [comment]
I've tried to generate via external API and it works fine but only on my local machine and on the build on netlify but on my own server doesn't work. Any idea why?

**Comment by harlan-zw** [comment]
> I've tried to generate via external API and it works fine but only on my local machine and on the build on netlify but on my own server doesn't work. Any idea why?

Hey, happy to help but you'll need to provide some reproduction details, ideally in a new issue.

**Comment by harlan-zw** [comment]
Will track this as part of https://github.com/harlan-zw/nuxt-simple-sitemap/issues/80
