### ISSUE TITLE
[nuxt] error caught during app initialization Error: Page not found: /sitemap.xml

### ISSUE THREAD

**Issue by mr-temi4** [harlan-zw/nuxt-simple-sitemap#68]
### Details

 am using nuxt app and pm2 on production. I have used @nuxtjs/sitemap for sitemap. When I do npm build and npm start on my local system, it works fine. But on production mydomain/sitemap.xml gives 404. It is not generating sitemap.xml
[https://stackoverflow.com/questions/59879355/nuxt-sitemap-xml-not-generating/76484315#76484315]

I have a similar problem with the sitemap, after build I give "[nuxt] error caught during app initialization Error: Page not found: /sitemap.xml"

**Comment by mr-temi4** [comment]
oh, sorry, you are right - really I am using nuxt-simple-sitemap. But I can`t install @nuxtjs/sitemap for nuxt3 and how I am understanding this module doesn't work with nuxt3 yet

**Comment by harlan-zw** [comment]
`@nuxtjs/sitemap` does not support Nuxt 3

This module does work on Nuxt 3.

**Comment by mr-temi4** [comment]
Yes, I have problems with **nuxt-simple-sitemap**, I hope you can help me.

I have an external API (it's a JSON that has a slug (loc), time update for each element that I use to create my sitemap on a website (for Google bot). In nuxt.config.ts I do that something like this:

`sitemap: {
    urls: async (): Promise<any> => {
      const data: any = await fetch('https://-------.com/api/sitemap')
      const routes = await data.json()
      const mainPages = [
        {
          loc: '/services',
          changefreq: 'daily',
          priority: 0.9
        },
      ]

      const slugPages = []

      for (const page in routes) {
        slugPages.push(...routes[page])
      }

      const fullConfig = slugPages.map(page => ({
        loc: page.slug,
        lastmod: page.updated,
        changefreq: 'daily',
        priority: 0.8
      }))

      return [...mainPages, ...fullConfig]
    },
  },`

But when we build project on our VPS we have 500 error page. For exmpl. If we deploy this project on netlify sitemap work correctly.

**Comment by harlan-zw** [comment]
Hi, please provide the stack trace or a reproduction, otherwise I can't help.

Also I'drecommend that you use https://github.com/harlan-zw/nuxt-simple-sitemap#handling-dynamic-urls
