### ISSUE TITLE
Fetching the sitemap on the server-side results in a 403 error with Cloudflare page

### ISSUE THREAD

**Issue by DanSnow** [harlan-zw/nuxt-simple-sitemap#69]
### Describe the bug

If you use another server route to fetch /sitemap.xml on a Cloudflare page, you will receive a 403 error.

## Reproduction Steps
On a Cloudflare page:

1. Create a server route, such as `/another-sitemap.xml`.
2. Use `$fetch` to fetch `/sitemap.xml` within the server route.
3. You will receive a 403 error.

Server log:
```plain
[nuxt] [request error] [unhandled] [403]  (403 Forbidden (http://localhost/__sitemap__/routes.json))
   at async $fetch2 (bundledWorker-0.24281922276911239.mjs:2340:13) 
   at async generateSitemapEntries (bundledWorker-0.24281922276911239.mjs:3649:16) 
   at async buildSitemap (bundledWorker-0.24281922276911239.mjs:3676:12) 
   at async bundledWorker-0.24281922276911239.mjs:3916:10
   at async Object.handler (bundledWorker-0.24281922276911239.mjs:1753:20)
   at async bundledWorker-0.24281922276911239.mjs:1796:7
   at async bundledWorker-0.24281922276911239.mjs:3972:20 
   at async $fetchRaw (bundledWorker-0.24281922276911239.mjs:2323:21)
   at async $fetch2 (bundledWorker-0.24281922276911239.mjs:2340:13)
   at async Object.handler (bundledWorker-0.24281922276911239.mjs:1753:20)
```

## Additional Context

Our use case requires:

1. Placing the sitemap in a location other than the default `/sitemap.xml`
2. Being able to make modifications before the sitemap is served

We would greatly appreciate any suggestions on how to achieve this.

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v20.3.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `yarn@4.0.0-rc.45`
- Builder:          `vite`
- User Config:      `modules`, `nitro`, `devtools`, `runtimeConfig`, `sitemap`
- Runtime Modules:  `nuxt-simple-sitemap@2.6.2`
- Build Modules:    `-`
```

**Comment by harlan-zw** [comment]
Hey @DanSnow, thanks for the issue.

I believe what you're coming across is a nitro limitation/bug around it changing the headers for nested internal fetches.

To focus on your use case specifically, I've implemented a `sitemapName` option which will let you rename the sitemap, available in [2.7.0](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v2.7.0).

```ts
export default defineNuxtConfig({
    sitemap: {
      sitemapName: 'another-sitemap.xml',
    },
})
```

Modifying the sitemap before it's served is already possible, here's a code sample:

```ts
import { defineNitroPlugin } from 'nitropack/runtime/plugin'
import type { SitemapRenderCtx } from "nuxt-simple-sitemap";

export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('sitemap:sitemap-xml', async (ctx: SitemapRenderCtx) => {
    console.log('Sitemap SSR hook')
  })
})
```

Will close for now, but me know if you need any further help.
