### ISSUE TITLE
Support i18n module

### ISSUE THREAD

**Issue by provok-it** [harlan-zw/nuxt-simple-sitemap#7]
### Describe the bug

By default nuxt-simple-sitemap generates pages components urls.
This clashes with pre-rendered routes and i18n.

We should be able to disable default urls generation (prevent generateUrls function from running) without excluding them one by one. 

### Reproduction
[Reproduction link](https://stackblitz.com/edit/github-maf42q?file=pages/index.vue)

- `yarn build`
- `open ./.output/public/sitemap.xml`

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.37 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 103.0.2
    Safari: 16.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey, thanks for the issue!

I've added the `inferStaticPagesAsRoutes` to escape from using `generateUrls`, available in 1.0.5.

```ts
export default defineNuxtConfig({
 sitemap: {
  inferStaticPagesAsRoutes: false,
 }
})
```

I'll be looking to support i18n properly soon, if you have any other ideas on what the integration should look like, please let me know :)

**Comment by provok-it** [comment]
@harlan-zw 
It works like a charm, thanks 👌

PS In the README.md, it is said that the `include` property default value is `undefined`.
While in reality, its default value (src/module.ts line 69) is `include: ['/**']`.
You should update the README properties values to reflect reality.

**Comment by harlan-zw** [comment]
> @harlan-zw It works like a charm, thanks ok_hand
> 
> PS In the README.md, it is said that the `include` property default value is `undefined`. While in reality, its default value (src/module.ts line 69) is `include: ['/**']`. You should update the README properties values to reflect reality.

Thanks, have updated the doc. Did you run into an issue with it being `['/**'*']`?

**Comment by provok-it** [comment]
Nope, no issues.

I find it weird to have `include` and `exclude` rules applied to both `urls` and `prerendedRoutes` since the challenges for those two arrays are different.

Plus, you run `urlFilter` two times.
The first time inside `generateUrls`, thus on the soon-to-be populated `urls` array.
The second time directly on the merged array `[...urls, ...prerendedRoutes]`.
Consequently, you run the filter function twice on a section of the final URLs.

**Comment by harlan-zw** [comment]
> Nope, no issues.
> 
> I find it weird to have `include` and `exclude` rules applied to both `urls` and `prerendedRoutes` since the challenges for those two arrays are different.
> 
> Plus, you run `urlFilter` two times. The first time inside `generateUrls`, thus on the soon-to-be populated `urls` array. The second time directly on the merged array `[...urls, ...prerendedRoutes]`. Consequently, you run the filter function twice on a section of the final URLs.

Agreed, the code isn't as good as it could be, optimised for doing what it needs to do. Will refactor it at some point when I add a new feature. Always happy to receive PRs too :P
