### ISSUE TITLE
No images detected (is nuxt-image supported?)

### ISSUE THREAD

**Issue by hartmut-co-uk** [harlan-zw/nuxt-simple-sitemap#70]
### Describe the bug

Hi, in my sitemap.xml there are 0 images detected across all pages.
Is the nuxt-simple-sitemap module working with nuxt-image?

Many thanks,
Hartmut

### Reproduction

https://thriving.dev/sitemap.xml

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `app`, `modules`, `build`, `content`, `runtimeConfig`, `image`, `nitro`, `tailwindcss`, `routeRules`, `sitemap`, `googleFonts`
- Runtime Modules:  `@nuxt/content@2.7.0`, `@nuxt/image-edge@1.0.0-rc.1-28116474.c4a8ff6`, `nuxt-icon@0.4.1`, `@nuxtjs/google-fonts@3.0.1`, `@nuxtjs/tailwindcss@6.7.2`, `@nuxtjs/plausible@0.2.1`, `@vueuse/nuxt@10.2.0`, `nuxt-simple-sitemap@2.7.0`
- Build Modules:    `-`
```

### relevant config from `nuxt.config.ts`
```ts
  nitro: { // https://nitro.unjs.io/config/#prerender
    prerender: {
      crawlLinks: true,
      routes: ['/']
    }
  },
  routeRules: {
    '/**': { sitemap: { changefreq: 'Monthly', priority: 0.1 } },
    '/': { sitemap: { changefreq: 'Daily', priority: 0.9 } },
    '/about': { sitemap: { changefreq: 'Monthly', priority: 0.4 } },
    '/roadmap': { sitemap: { changefreq: 'Monthly', priority: 0.3 } },
    '/courses': { sitemap: { changefreq: 'Monthly', priority: 0.5 } },
    '/courses/**': { sitemap: { changefreq: 'Monthly', priority: 0.8 } },
    '/blog/**': { sitemap: { changefreq: 'Daily', priority: 0.5 } },
    '/blog/tags/**': { sitemap: { changefreq: 'daily', priority: 0.2 } },
  },
  sitemap: {
    exclude: [
      '/legal',
    ],
  },
```

**Comment by harlan-zw** [comment]
Hi @hartmut-co-uk, thanks for the issue.

Images will only be automatically discovered if you're prerendering your app. Can you confirm how you're deploying it?

**Comment by hartmut-co-uk** [comment]
Hi @harlan-zw thanks for the response. I'm deploying with vercel, default 'Nuxt Deployment Settings' (should be `nuxi build`).

I've added the config for nitro to my above post. (using `nitro.prerender.crawlLinks: true`)

**Comment by hartmut-co-uk** [comment]
I just run `yarn generate` from my local machine and it looks like images are detected and included!

Let me try to explore if/how I can change my vercel deployment. Static build is on my roadmap anyway but was long blocked by nuxt-image pretender feature - which I think is now working.

**Comment by hartmut-co-uk** [comment]
Thanks again for the quick reply and for pointing me in the right direction.
I have now moved to full static pre-rendered deployment.
Image detection can only work for prerendering as suggested so I'm closing this issue.
