### ISSUE TITLE
Disable generated by message

### ISSUE THREAD

**Issue by mrspence** [harlan-zw/nuxt-simple-sitemap#74]
### Describe the bug

The generated sitemap includes a message "generated by nuxt-simple-sitemap.xml" with no clear way to remove this.

![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/30320791/c331a0cd-7e4f-4a6e-b870-5866b09274fc)

This problem has been raised before (https://github.com/harlan-zw/nuxt-simple-sitemap/issues/64), but the solution only fixes a styled `xsl` sitemap. Plain XML sitemaps still include a "generated by" comment.

This could be an "opt out" configuration flag, that is documented with a message encouraging those who wish to turn it off to check out the [Sponsor this repo](https://github.com/sponsors/harlan-zw) promo page

**Comment by harlan-zw** [comment]
I think adding a config to disable this is a reasonable suggestion.

At a minimum, you should be able to remove this using the hooks, but I don't think that's possible either.

**Comment by harlan-zw** [comment]
You now can provide the `credits: false` option to disable this in v3.
