### ISSUE TITLE
Alternative href links not matching routes when using i18n with different routes/slugs for each lang

### ISSUE THREAD

**Issue by FabianEllenberger** [harlan-zw/nuxt-simple-sitemap#76]
### Details

I'm using nuxt/i18n with the `prefix_except_default` strategy. The sitemap is being generated but some alternate links are not correct, they should have a different slug (href) on english then on the default language german.

For example the route `/ueber-uns` in the German version is `/en/about` in English. This is being defined inside nuxt/i18n via `definePageMeta`:
```javascript
definePageMeta({ 
  nuxtI18n: data.value.other_languages // 'about-us'
})
```

Also the generated `routes.json` seems to include all the translations correctly:
```json
["/","/ueber-uns","/en","/en/about-us"]
```

But the sitemap just uses the default route and adds the prefix – current output:
```
<url>
  <loc>http://localhost:3000/ueber-uns</loc>
  <xhtml:link rel="alternate" hreflang="en" href="http://localhost:3000/en/ueber-uns" />
</url>
```

Expected output:
```
<url>
  <loc>http://localhost:3000/ueber-uns</loc>
  <xhtml:link rel="alternate" hreflang="en" href="http://localhost:3000/en/about-us" />
</url>
```

The alternate link should have a href including it's correct route `/en/about-us`.

Is there maybe a way to update the alternative link for a route inside a hook, or is this behavior no supported yet?
Many thanks in advance and thanks for the module!

**Comment by harlan-zw** [comment]
Thanks, will track here: https://github.com/harlan-zw/nuxt-simple-sitemap/issues/76
