### ISSUE TITLE
Add gzip compression 

### ISSUE THREAD

**Issue by jerrywangmm** [harlan-zw/nuxt-simple-sitemap#77]
### Details

code:
sitemap: {
    siteUrl: "https://test.com/",
    defaults: { lastmod: new Date(), changefreq: "always" },
    exclude: ["/detail"],
    urls: async () => {
      let routes: any = [
        {
          url: "/",
          changefreq: "always",
          priority: 1,
          lastmod: new Date(),
        },
      ];
      let addArr: any = [];
      let res1: any = await fetch(
        "https://api.test.com/api/sitemap",
        {
          method: "GET",
        }
      )
        .then((response) => response.json())
        .then((data) => data);
      res1.data.map((item) => {
        addArr.push({
          url: `/detail/${item.name
            .replace(/[^a-zA-Z0-9\\s]/g, "-")
            .toLowerCase()}-${item.id}/`,
          changefreq: "always",
          priority: 0.8,
          lastmod: new Date(),
        });
      });
      routes = routes.concat(addArr);
      return routes;
    },
  },

**Comment by jerrywangmm** [comment]
can generate sitemap.xml.gz is，like nuxt2

**Comment by wokalek** [comment]
This setting doesn't help?

```
nitro: {
    compressPublicAssets: true
}
```

**Comment by harlan-zw** [comment]
> This setting doesn't help?
> 
> ```
> nitro: {
>     compressPublicAssets: true
> }
> ```

This should work when the sitemap is prerendered, I'm guessing they want support for nitro to gzip the runtime sitemap.

I'm not aware of Nitro supporting this yet, so I'll need to wait.
