### ISSUE TITLE
dynamicUrlsApiEndpoint is undefined after deployment

### ISSUE THREAD

**Issue by kaboume** [harlan-zw/nuxt-simple-sitemap#78]
### Details

Hi,
I'm using pm2 to run my Nuxt3 application in production.
The Nuxt3 front end has a backend node Js API which builds urls for sitemap : https://api.website.com/v1/misc/sitemap

Here is my nuxt-config file : 

```
  sitemap: {
    dynamicUrlsApiEndpoint: `${process.env.NUXT_PUBLIC_API_BASE_URL}misc/sitemap`,
    inferStaticPagesAsRoutes: false,
  },
```

Everything works fine on local but after deployment, dynamicUrlsApiEndpoint is undefined.

Here is my pm2.json file : 

```
{
    "apps": [
      {
        "name": "website.com",
        "exec_mode": "fork",
        "script": "PORT=3000 NITRO_PORT=3000 NUXT_PUBLIC_API_BASE_URL=https://api.website.com/v1/ node .output/server/index.mjs",
        "cwd": "/var/www/website.com",
        "autorestart": true,
        "watch": false,
        "max_memory_restart": "1G",
        "env": {
          "NODE_ENV": "development"
        },
        "env_production": {
          "NODE_ENV": "production"
        }
      },
```

Have you got an idea ?

**Comment by kaboume** [comment]
can anyone help me ?

**Comment by slavanossar** [comment]
The template literal being used for `dynamicUrlsApiEndpoint` is evaluated during the `build` task, but you are only providing the environment variable when starting the server, meaning it's not available during `build`.

You can create a `.env` file in your project root and include the `NUXT_PUBLIC_API_BASE_URL` variable there.

```env
# .env
NUXT_PUBLIC_API_BASE_URL="https://api.website.com/v1/"
```

**Comment by kaboume** [comment]
@slavanossar thanks a lot !!!
it works great :)
