### ISSUE TITLE
Module is not working in development mode

### ISSUE THREAD

**Issue by Momme97** [harlan-zw/nuxt-simple-sitemap#8]
### Describe the bug

Module does not work correctly in development mode. In Production mode everything is fine.

const { SitemapStream, streamToPromise } = pkg;

  import { SitemapStream, streamToPromise } from 'node_modules/sitemap/dist/index.js';                                                                                                                                   17:11:18
  ^^^^^^^^^^^^^
  SyntaxError: Named export 'SitemapStream' not found. The requested module 'node_modules/sitemap/dist/index.js' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'node_modules/sitemap/dist/index.js';
  const { SitemapStream, streamToPromise } = pkg;
  
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
  at async loadESM (node:internal/process/esm_loader:91:5)
  at async handleMainPromise (node:internal/modules/run_main:65:12)

ℹ Vite client warmed up in 1991ms                                  

### System Info

```Shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.20 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 108.0.1
    Safari: 15.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @Momme97 

Can you check that you don't have a different dependency that uses `sitemap`.

You can run `npm why sitemap` 

You should be using `"sitemap": "^7.1.1",`

**Comment by Momme97** [comment]
Hey @harlan-zw ,
thanks for your answer. There was a second dependency using that uses sitemap.
But the problem still exist after removing the conflicting dependency.

`sitemap@7.1.1 dev
node_modules/nuxt-simple-sitemap/node_modules/sitemap
  sitemap@"^7.1.1" from nuxt-simple-sitemap@1.0.6
  node_modules/nuxt-simple-sitemap
    dev nuxt-simple-sitemap@"^1.0.6" from the root project
`

` worker reload] [worker init] Cannot find package 'sitemap' imported from `

**Comment by harlan-zw** [comment]
> Hey @harlan-zw , thanks for your answer. There was a second dependency using that uses sitemap. But the problem still exist after removing the conflicting dependency.
> 
> `sitemap@7.1.1 dev node_modules/nuxt-simple-sitemap/node_modules/sitemap sitemap@"^7.1.1" from nuxt-simple-sitemap@1.0.6 node_modules/nuxt-simple-sitemap dev nuxt-simple-sitemap@"^1.0.6" from the root project `
> 
> `worker reload] [worker init] Cannot find package 'sitemap' imported from`

Try clearing all .nuxt / node_modules / lock file and re-install. Seems like Nuxt can't find the sitemap npm module

**Comment by Momme97** [comment]
Thanks for your support and great work btw !
