### ISSUE TITLE
Support i18n build-time macros (definePageMeta, defineI18nRoute)

### ISSUE THREAD

**Issue by harlan-zw** [harlan-zw/nuxt-simple-sitemap#82]
### Describe the bug

https://github.com/harlan-zw/nuxt-simple-sitemap/issues/79
https://github.com/harlan-zw/nuxt-simple-sitemap/issues/76
https://github.com/harlan-zw/nuxt-simple-sitemap/issues/66
https://github.com/harlan-zw/nuxt-simple-sitemap/issues/63

Currently, build-time i18n macros aren't being passed to generate the sitemap. Need to hook into this somehow.

**Comment by harlan-zw** [comment]
Now supported in [version 3](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v3.0.0).

@Phillocity, @FabianEllenberger, @apsyleg, @mradenkovic

Let me know if you have any issues.

**Comment by apsyleg** [comment]
@harlan-zw Cool, thanks! Trying to test, but have an issue
