### ISSUE TITLE
How to pregenerate sitemap with nuxt build.

### ISSUE THREAD

**Issue by bartligthart** [harlan-zw/nuxt-simple-sitemap#83]
### Details

I have about 70k pages and use the normal `nuxt build` on Netlify. And use the _sitemap-urls.ts server api file to generate all these links. 

But it takes a while to generate, so too long and gives me timeout errors. So I'm looking to prerender the sitemap with build. But can't really figure out how to do this. 

nuxt.config.ts
```
  sitemap: {
    siteUrl: 'https://URL.com',
    sitemaps: true
  },
  ```
  
  Great package btw! Love it!

**Comment by harlan-zw** [comment]
Hey, thanks! That's a lot of URLs.

You should just be able to include it in the prerender list.

```ts
export default defineNuxtConfig({
   nitro: {
    prerender: {
      routes: [
        '/robots.txt',
      ]
    }
  },
})
```

**Comment by bartligthart** [comment]
Yes this works great! Thanks!
