### ISSUE TITLE
Cant change url setting on dev mode

### ISSUE THREAD

**Issue by wokalek** [harlan-zw/nuxt-simple-sitemap#86]
### Describe the bug

Tried to set 
```ts
export default defineNuxtConfig({
  site: {
    url: 'https://example.com',
  },
})
```

And this in `.env`
```env
NUXT_PUBLIC_SITE_URL=https://example.com
```

But it still have localhost in `/sitemap.xml`

![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/23037847/d5097ea6-a8df-4bb3-a066-068172d379b6)

### System / Nuxt Info

```Shell
- Operating System: Linux
- Node Version:     v20.3.1
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.5
- Builder:          vite
- User Config:      telemetry, srcDir, app, modules, runtimeConfig, vite, css, postcss, colorMode, device, image, content, pwa, robots, site, sitemap, schemaOrg
- Runtime Modules:  @nuxtjs/robots@3.0.0, @nuxtjs/color-mode@3.3.0, @nuxtjs/fontaine@0.4.0, @nuxtjs/device@3.1.0, @nuxt/content@2.7.0, @nuxt/image@1.0.0-rc.1, @vueuse/nuxt@10.2.1, @vite-pwa/nuxt@0.1.0, nuxt-typed-router@3.2.4, nuxt-svgo@3.2.0, nuxt-simple-sitemap@3.0.5, nuxt-schema-org@2.2.0, nuxt-lodash@2.5.0
- Build Modules:    -
```

**Comment by wokalek** [comment]
Have this error in playground of this repo.

![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/23037847/80c479d8-9aba-42f6-87da-3d8453333bb7)

**Comment by wokalek** [comment]
Seems like NUXT_PUBLIC_SITE_URL no used at all.

**Comment by harlan-zw** [comment]
Very strange, investigating!

**Comment by harlan-zw** [comment]
Hi, by default the request origin is used for development so you can click through to your links easier.

If you'd like to see the real URL you can build/generate.

I agree this can be a bit confusing though, some ideas on improvements:
- have a way to show the canonical URL in development (config option and / or query param)
- add an item in the tips explaining this behavior

Let me know if you have any other ideas!

**Comment by wokalek** [comment]
Not it's doing nothing.

**Comment by harlan-zw** [comment]
> > Hi, by default the request origin is used for development so you can click through to your links easier.
> 
> This is not the expected use case. I want to know that the sitemap is generated correctly before deploying to production.
> 
> Previously, the setup `{ site: { url: 'http://test.test' } }` worked in the expected way. Why has this behavior changed?

This is a valid use case, and why I suggested the improvements. 

Personally, I prefer this for development so I can navigate my site easier. It also avoids confusing the development sitemap preview to the real thing, for prerendered sites they can be quite different.

The only fail-safe way to make sure your sitemap is working is to test it after a build.

**Comment by wokalek** [comment]
> Personally, I prefer this for development so I can navigate my site easier. It also avoids confusing the development sitemap preview to the real thing, for prerendered sites they can be quite different.

So, then, you need to indicate next to the setting that it will be applied only in production mode. I didn't see this setting in the documentation.



> The only fail-safe way to make sure your sitemap is working is to test it after a build.

That's why I have this (:

#85

**Comment by harlan-zw** [comment]
Try out 3.0.6 and let me know if you consider this fixed
