### ISSUE TITLE
Multiple sitemaps support

### ISSUE THREAD

**Issue by VladStepanov** [harlan-zw/nuxt-simple-sitemap#9]
### Clear and concise description of the problem

As a developer, who migrating from nuxt2 to nuxt3, i want nuxt sitemap module that can generate multiple sitemaps.

### Suggested solution

There is sitemap module for nuxt 2 with multi-sitemap support: https://sitemap.nuxtjs.org/usage/sitemap-index#setup-a-list-of-sitemaps

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by harlan-zw** [comment]
Support is planned for this

**Comment by modbender** [comment]
Waiting for the same.

**Comment by harlan-zw** [comment]
Hey @VladStepanov and @modbender 

Thanks for your patience, this is now supported in v2. Please see the [Multiple Sitemap Support](https://github.com/harlan-zw/nuxt-simple-sitemap#multiple-sitemap-support) docs.
