### ISSUE TITLE
Sitemap Entries Missing for URLs with Parameters

### ISSUE THREAD

**Issue by samargulies** [harlan-zw/nuxt-simple-sitemap#92]
### Describe the bug

I am manually adding URLs to my sitemap with a format like: `"/info?county=Philadelphia&country=US"`. When I look at the sitemap, it appears that the URLs are all being combined into the entry for `"/info"`, with all the other URLs missing.

Reproduction:

Add this to `nuxt.config.ts`:
```ts
export default defineNuxtConfig({
 sitemap: {
    // provide dynamic URLs to be included
    urls: () => {
      return ["/test", "/test?a=1", "/test?a=2", "/test?b=1"];
    },
  },
});
```

Expected Result:

Entries in `/sitemap.xml` for /test, /test?a=1, etc.

Actual Result:

One entry for /test.

**Comment by harlan-zw** [comment]
Hey @samargulies, thanks for the issue.

I've pushed up a fix for this in 3.0.10. Let me know if you have any further issues :)
