### ISSUE TITLE
TypeError: Could not load virtual:#nuxt-simple-sitemap/pages.mjs (defineI18nRoute)

### ISSUE THREAD

**Issue by apsyleg** [harlan-zw/nuxt-simple-sitemap#94]
### Describe the bug

Hi! I am trying to use `nuxt-simple-sitemap` with `@nuxtjs/i18n`
When using build-time macro `defineI18nRoute` I got an error when starting project

I have a reproduction [here](https://stackblitz.com/edit/nuxt-starter-buwx4g?file=pages%2Ftak.vue)
If we remove `defineI18nRoute` from `tak.vue` there will be no error

<img width="653" alt="image" src="https://github.com/harlan-zw/nuxt-simple-sitemap/assets/13366012/1579e56b-d089-49b6-9010-c38d05993956">

### Reproduction

https://stackblitz.com/edit/nuxt-starter-buwx4g?file=pages%2Ftak.vue

### System / Nuxt Info
-- @nuxtjs/i18n@8.0.0-beta.13
-- nuxt-simple-sitemap@3.0.11
-- nuxt@3.6.5

**Comment by andysay** [comment]
@harlan-zw    ERROR  TypeError: Could not load virtual:#nuxt-simple-sitemap/pages.mjs (imported by node_modules/nuxt-simple-sitemap/dist/runtime/routes/debug.mjs): Cannot read properties of undefined (reading 'includes')  still have

**Comment by harlan-zw** [comment]
Hmm, I've pushed out 3.1.8 which may help with that. Otherwise could you provide a reproduction :pray:
