### ISSUE TITLE
About `autoAlternativeLangPrefixes`

### ISSUE THREAD

**Issue by rcerljenko** [harlan-zw/nuxt-simple-sitemap#95]
### Details

Hi there,

How exactly does [`autoAlternativeLangPrefixes`](https://nuxtseo.com/sitemap/api/config#autoalternativelangprefixes) work. As I see from docs it states the following:
```
Automatically add alternative language prefixes for each entry with the given prefixes. Set to false to disable.
When using the @nuxtjs/i18n module, this will automatically be set to the configured locales when left undefined.
```

I am using the i18n module so I left it undefined (not set at all) but I'm not getting auto-prefixed URLs.

My `nuxt.config.ts`:
```js
i18n: {
	baseUrl: BASE_APP_URL,
	langDir: 'locales/',
	locales: [
		{
			code: 'hr',
			iso: 'hr-HR',
			file: 'hr.ts'
		},
		{
			code: 'en',
			iso: 'en-US',
			file: 'en.ts'
		}
	],
	detectBrowserLanguage: false,
	defaultLocale: 'hr',
	vueI18n: './nuxt-i18n.ts'
}
```

And `nuxt-i18n.ts`:
```js
export default defineI18nConfig(() => ({
	legacy: false,
	locale: 'hr',
	fallbackLocale: 'hr'
}))
```

**Comment by harlan-zw** [comment]
Hey, thanks for the issue.

Can you try out [v3.0.14](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v3.0.14) and let me know if it's working better?

**Comment by rcerljenko** [comment]
Still the same...
This is how i test:
```
nuxt build
nuxt preview
```

**Comment by harlan-zw** [comment]
There was one other small bug I found and pushed up a fix in 3.0.15. I tested it out here https://stackblitz.com/edit/nuxt-starter-jwuie4?file=app.vue

Seems to be working so will close this off, please modify the StackBlitz if I missed something.

**Comment by rcerljenko** [comment]
It works thanks! It would be cool if you could completly disable caching in dev mode since you can't test changes like this one

**Comment by harlan-zw** [comment]
> It works thanks! It would be cool if you could completly disable caching in dev mode since you can't test changes like this one

Caching should definitely be disabled in dev :thinking: Do you mean for the dynamic URLs?

**Comment by rcerljenko** [comment]
yes... eg: I've later added another laguage in the array (third one) but sitemap still rendered two of them (old ones)
