### ISSUE TITLE
Info about include / exclude glob patterns

### ISSUE THREAD

**Issue by Archetipo95** [harlan-zw/nuxt-simple-sitemap#96]
### Details

I'm tring to match and include all my urls that start with `/p-` but it's like it's not working. I tried the regex `^/p-.+` and `/p-.+` but with no luck.

P.S.:
I also tried `/p-**` and `/p-*`

P.P.S.:
These are some of the urls that I need to include
```
http://localhost:3000/p-sebamed-latte-idratante-200ml
http://localhost:3000/p-sensodyne-f-previon-100ml
http://localhost:3000/p-silivis-integratore-capelli-e-unghie-90g
```

**Comment by Archetipo95** [comment]
Ok found the solution! This is the correct way:
` include: ["/p-/**"]`

**Comment by harlan-zw** [comment]
Hey :)

So the include/exclude rules use the same logic as the route rule parsing, which I'm guessing doesn't support ** in the middle of a URL. 

I'll keep this open so remind myself to add proper docs around this and see if it can be fixed upstream.

**Comment by harlan-zw** [comment]
Now documented with the [v4 release](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v4.0.0)

https://nuxtseo.com/sitemap/guides/filtering-urls
