### ISSUE TITLE
Manual chunking + Automatic Chunking

### ISSUE THREAD

**Issue by Archetipo95** [harlan-zw/nuxt-simple-sitemap#97]
### Details

Is it possible to split custom sitemaps and decide how many URLs to keep?
My current problem is that we have 30k URLs products, and the SEO department asked to split multi sitemap at 5k/10k URLs per sitemap.

So I'm wandering if there is a way to do this.

**Comment by harlan-zw** [comment]
Hey, this sounds quite possible.

Currently, it splits into separate sitemaps per 1k urls using https://nuxtseo.com/sitemap/guides/multi-sitemaps#automatic-chunking.

You would want a config value like `automaticSitemapsChunkSize: <value>` that would let you split them at 5k or 10k urls?

The alternative is to chunk manually https://nuxtseo.com/sitemap/guides/multi-sitemaps#manual-chunking?

**Comment by Archetipo95** [comment]
Using the automaticSitemapsChunkSize: <value> feature would be really helpful. Currently, I'm getting all my URLs from a dynamic API and then manually splitting them into multiple sitemaps. But from what I can see in the documentation, there is no option like SitemapsChunkSize: <value> to automatically split the custom sitemaps.

**Comment by harlan-zw** [comment]
I see, thanks for the explanation.

This sounds quite possible but will require a bit of work. Will try to get around to it when I have some availability.

**Comment by harlan-zw** [comment]
I think this will be too much work for quite a specific use case, so I'm going to close this issue.

Also it does seem possible to solve this on your end with the new [v4 release](https://github.com/harlan-zw/nuxt-simple-sitemap/releases/tag/v4.0.0).
You would just need to query the total count of records and dynamically create the sitemap config when your Nuxt app starts.
